"""Build tests/fixtures.js from real model folders: path, size, and the first lines of text files.
Only headers are stored (that is where version stamps and format signatures live), never full model data."""
import os, sys, json

MAXL = 120
KEY = {'file.cio','gwflow.input','time.sim','print.prt','codes.bsn','mfsim.nam','output.std'}
NL = chr(10)
BIN = {'exe', 'dll', 'sqlite', 'db', 'hds', 'cbc', 'bin', 'zip', 'shp', 'dbf', 'shx', 'sbn', 'sbx', 'prj', 'cpg',
       'xml', 'mxd', 'pptx', 'docx', 'xlsx', 'xlsm', 'pdf', 'png', 'jpg', 'tif', 'gz', '7z', 'bak', 'tpl'}


def entry(root, rel):
    p = os.path.join(root, rel)
    size = os.path.getsize(p)
    b = os.path.basename(rel)
    ext = b.rsplit('.', 1)[-1].lower() if '.' in b else ''
    text = None
    if ext not in BIN and size > 0:
        try:
            with open(p, 'rb') as fh:
                raw = fh.read(65536)
            if b'\x00' not in raw:
                txt = raw.decode('utf-8', 'ignore').replace(chr(13) + NL, NL)
                lines = txt.split(NL)
                if b.lower() in KEY or b.lower().endswith(('.nam', '.mfn', '.lst')):
                    text = NL.join(l[:300] for l in lines[:MAXL])
                else:
                    text = NL.join(l[:200] for l in lines[:3])
        except Exception:
            pass
    return {'path': rel.replace(chr(92), '/'), 'size': size, 'text': text}


def walk(root, maxdepth=1):
    out = []
    root = os.path.normpath(root)
    for d, dirs, files in os.walk(root):
        depth = 0 if d == root else os.path.relpath(d, root).count(os.sep) + 1
        if depth >= maxdepth:
            dirs[:] = []
        for f in files:
            out.append(os.path.relpath(os.path.join(d, f), root))
    return out


# folders to read: key fixture_sources in bench/hydra_bench.config.json = list of {name, dir, depth} (see bench/config.py)
sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'bench'))
import config
CASES = [(c['name'], c['dir'], int(c.get('depth', 1))) for c in config.get('fixture_sources')]
out = {}
for name, path, depth in CASES:
    if not os.path.isdir(path):
        print('MISSING', name)
        continue
    rels = walk(path, depth)
    out[name] = {'source': name, 'entries': [entry(path, r) for r in rels]}
    print(name + ': ' + str(len(rels)) + ' files')

dest = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(os.path.abspath(__file__)), 'fixtures.js')
with open(dest, 'w', encoding='utf-8') as fh:
    fh.write('/* generated by make_fixtures.py from real model folders (headers only) */' + NL)
    fh.write('window.HDA_FIXTURES = ' + json.dumps(out) + ';' + NL)
print('wrote fixtures.js', os.path.getsize(dest) // 1024, 'KB')
