/* Writes docs/ADVICE_INVENTORY.md: every finding the tool can produce, with severity, the current title and text, the evidence behind it,
 * and whether it has advice in plain words.   node tests/make_advice_inventory.js
 * The titles, severities and texts are taken from the rules themselves by firing each one on the fixtures of tests/advice_triggers.js. */
'use strict';
const fs = require('fs');
const path = require('path');
const { runRules, HDA } = require('./rules_harness');
const { TRIGGER, CHAR_UPLOADS } = require('./advice_triggers');

const cell = s => String(s == null ? '' : s).replace(/<[^>]+>/g, '').replace(/&gt;/g, '>').replace(/&lt;/g, '<').replace(/&amp;/g, '&').replace(/\|/g, '/').replace(/\s+/g, ' ').trim();
const cut = (s, n) => { s = cell(s); return s.length > n ? s.slice(0, n - 1).replace(/\s+\S*$/, '') + ' ...' : s; };
const ENG = a => !a.engine ? 'none' : (Array.isArray(a.engine) ? a.engine : [a.engine]).map(e => '#' + e.pilot).join(', ');

let md = '# Advice inventory: every finding Hydra Check can produce\n\n' +
  'Generated by `node tests/make_advice_inventory.js` from the rules themselves (each rule is fired on a small fixture from `tests/advice_triggers.js`), so the titles, severities and texts below are the current ones.\n\n' +
  'How to read the columns:\n\n' +
  '- **Evidence**: how we know the finding is right and what the engine does. `measured here` = reproduced on a real engine in the injected-fault benchmark (`results/pilot_table.md`, the pilot case number is given) or in the precision audit; `read in the engine source`; `documented`; `community-reported` (not reproduced here).\n' +
  '- **Plain version**: whether a plain-language version existed before this change. For the rule findings the existing text (`detail`, `fix`) is technical; the characterization messages were already plain sentences but had no steps.\n' +
  '- **Advice now**: all of them have `plain`, `why`, `steps`, `verify` and `evidence` (`src/advice.js`). **Engine line** = a "what the engine itself said" line from the pilot table (case numbers).\n\n';

const rows = [];
for (const adv of HDA.ADVICE) {
  const t = TRIGGER[adv.id];
  const res = runRules(t[1], t[0], t[2] || Object.keys(t[1])).filter(f => f.id === adv.id);
  const f = res[0];
  rows.push({ adv, f });
}
md += '## Findings from the rules (' + rows.length + ')\n\n';
md += '| id | family | severity | current title | current text (detail, shortened) | evidence | engine line | plain version before | advice now |\n|---|---|---|---|---|---|---|---|---|\n';
for (const { adv, f } of rows) {
  const sev = adv.id === 'swatplus.table_rows' ? 'error (hru-data.hru) / warning (other tables)' :
              adv.id === 'generic.empty_files' ? 'error (time.sim, .sol) / warning (other files)' : f.sev;
  md += `| \`${adv.id}\` | ${adv.family} | ${sev} | ${cell(f.title)} | ${cut(f.detail, 220)} | ${adv.evidence.kind}: ${cut(adv.evidence.ref, 110)} | ${ENG(adv)} | no | yes |\n`;
}

md += '\n## Messages from the characterization (' + HDA.CHAR_ADVICE.length + ')\n\n';
md += 'These come from `src/characterize.js` (what the tool saw in how the files sit together). They are shown as "problems" (red), "Missing, and why it matters", "Could be read two ways" and "Worth knowing".\n\n';
const SEV = { problems: 'error ("will stop the run")', missing: 'warning', ambiguity: 'warning', notes: 'ok (note)' };
md += '| id | kind | severity | current text | evidence | engine line | plain version before | advice now |\n|---|---|---|---|---|---|---|---|\n';
for (const a of HDA.CHAR_ADVICE) {
  md += `| \`${a.id}\` | ${a.kind} | ${SEV[a.kind]} | ${cut(a.sample, 200)} | ${a.evidence.kind}${a.evidence.inferred ? ' (tool inference)' : ''}: ${cut(a.evidence.ref, 110)} | ${ENG(a)} | partly (plain sentence, no steps) | yes${a.unreachable ? ' (the message cannot be produced today: its condition is never met by the current detection)' : ''} |\n`;
}

md += '\n## Two cards that are not findings\n\n' +
  '- "We could not tell which model this is" (`src/char_ui.js`): already written in plain words with a "What you can do" line; no change.\n' +
  '- "No known error signatures detected" (`renderFindings`): already plain; no change.\n\n' +
  '## Evidence summary\n\n';
const all = HDA.ADVICE.concat(HDA.CHAR_ADVICE);
for (const k of HDA.EVIDENCE_KINDS) md += `- ${k}: ${all.filter(a => a.evidence.kind === k && !a.evidence.inferred).length}\n`;
md += `- tool inference (filed as community-reported, shown on the page as "inferred from your files, not tested"): ${all.filter(a => a.evidence.inferred).length}\n`;
const ids = l => l.map(a => '`' + a.id + '`').join(', ');
md += `\nWeakly evidenced, community-reported and not reproduced here: ${ids(all.filter(a => a.evidence.kind === 'community-reported' && !a.evidence.inferred))}.\n`;
md += `\nWeakly evidenced, tool inference from the files in the upload (no engine behind it): ${ids(all.filter(a => a.evidence.inferred))}.\n`;
const pil = [...new Set(all.reduce((l, a) => l.concat(a.engine ? (Array.isArray(a.engine) ? a.engine : [a.engine]).map(e => e.pilot) : []), []))].sort((x, y) => x - y);
md += `\nPilot cases (results/pilot_table.md) with an engine line: ${pil.map(x => '#' + x).join(', ')}. Pilot case #1 (APEX, HOUSTON.SOL deleted) has no rule: the tool stayed silent and APEX finished normally, so there is nothing to advise.\n`;

fs.mkdirSync(path.join(__dirname, '..', 'docs'), { recursive: true });
fs.writeFileSync(path.join(__dirname, '..', 'docs', 'ADVICE_INVENTORY.md'), md);
console.log('wrote docs/ADVICE_INVENTORY.md: ' + rows.length + ' findings, ' + HDA.CHAR_ADVICE.length + ' characterization messages');
