/* Rule-level regression tests (the page's own rules, run headless):  node tests/run_rules_node.js
 * Each case documents WHY the rule must (or must not) fire. The "real model" cases are skipped when the folder is absent. */
'use strict';
const fs = require('fs');
const { runRules, loadFolderFull, HDA } = require('./rules_harness');

const NL = '\n';
const SOIL_HDR = 'name nly hyd_grp dp_tot anion_excl perc_crk texture dp bd awc soil_k carbon clay silt sand rock alb usle_k ec caco3 ph';
const soil1 = (name, tex, bd) => [name, 2, 'C', '1060.0', '0.5', '0.5', tex, '100.0', bd, '0.1', '10.0', '1.0', '20.0', '40.0', '40.0', '0.0', '0.01', '0.3', '0.0', '0.0', '7.5'].join(' ');
const soil2 = '1060.0 1.5 0.1 5.0 0.5 25.0 35.0 40.0 0.0 0.01 0.3 0.0 0.0 7.5';
const soils = (...rows) => ['soils.sol: test', SOIL_HDR].concat(rows).join(NL);

const cio = (nbyr, idaf, idal) => [' General input/output', ' ' + nbyr + ' | NBYR : Number of years simulated', ' 1985 | IYR : Beginning year', ' ' + idaf + ' | IDAF : Beginning julian day', ' ' + idal + ' | IDAL : Ending julian day'].join(NL);
const dis = (nper, itmuni, periods) => ['# MODFLOW DIS', '     1    23    40  ' + nper + '    ' + itmuni + '     2 # NLAY, NROW, NCOL, NPER, ITMUNI, LENUNI', '     0 # LAYCB', 'CONSTANT 1.000E+003 # DELR']
  .concat(periods.map(p => '   ' + p[0] + '  ' + p[1] + '  1.000000000000E+000  ' + (p[2] || 'TR') + ' # PERLEN NSTP TSMULT Ss/tr')).join(NL);

const titles = r => r.map(f => f.sev + ':' + f.title);
const has = (r, re) => r.some(f => re.test(f.title));

/* MODFLOW 6 fixtures. The listing lines are copied from real MODFLOW 6.7.0 runs of a FloPy toy model with OUTER_MAXIMUM 1 (with and without the CONTINUE option). */
const MF6_NAM = 'BEGIN models' + NL + '  gwf6  gwf.nam  gwf' + NL + '  gwt6  gwt.nam  gwt' + NL + 'END models' + NL + 'BEGIN solutiongroup  1' + NL + '  ims6  gwf.ims  gwf' + NL + '  ims6  gwt.ims  gwt' + NL + 'END solutiongroup  1';
const ims = (blockName, body) => '# File generated by Flopy' + NL + 'BEGIN options' + NL + '  COMPLEXITY  moderate' + NL + 'END options' + NL + NL + 'BEGIN ' + blockName + NL + '  ' + body + NL + 'END ' + blockName + NL;
const mf6 = (gwfIms, gwtIms) => ({ 'mfsim.nam': MF6_NAM, 'gwf.ims': gwfIms, 'gwt.ims': gwtIms || ims('nonlinear', 'OUTER_MAXIMUM  50') });
const LST_FAIL = ' Solution 1 did not converge for stress period 1 and time step 1' + NL + NL + ' Solution Group 1 did not converge for stress period 1 and time step 1' + NL + ' Simulation convergence failure. Simulation will terminate after output and deallocation.' + NL + NL + ' Elapsed run time:  0.039 Seconds' + NL + NL + 'ERROR REPORT:' + NL + NL + '  1.  Simulation convergence failure occurred 1 time(s).' + NL + ' Premature termination of simulation.';
const LST_CONT = ' Solution 1 did not converge for stress period 1 and time step 1' + NL + ' Solution 1 did not converge for stress period 1 and time step 2' + NL + NL + ' Elapsed run time:  0.073 Seconds' + NL + NL + 'WARNING REPORT:' + NL + NL + '  1.  Simulation convergence failure occurred 20 time(s).' + NL + ' Normal termination of simulation.';
const LST_OK = ' 1 CALLS TO NUMERICAL SOLUTION IN TIME STEP 4 STRESS PERIOD 5' + NL + ' 0 TOTAL ITERATIONS' + NL + ' Elapsed run time:  0.150 Seconds' + NL + ' Normal termination of simulation.';
const mf6r = files => runRules(files, 'modflow6', Object.keys(files));


const cases = [
  /* ---- soilNulls: only numeric columns are judged ---- */
  { name: 'soils.sol: "null" in the texture column is normal and is not flagged', fw: 'swat_plus',
    files: { 'soils.sol': soils(soil1('S1', 'null', '1.4'), soil2, soil1('S2', 'Loam', '1.3'), soil2) },
    expect: r => !has(r, /soils\.sol/) },
  { name: 'soils.sol: null in a numeric column (bd) is an ERROR that names the column', fw: 'swat_plus',
    files: { 'soils.sol': soils(soil1('S1', 'Loam', 'null'), soil2) },
    expect: r => r.some(f => f.sev === 'error' && /Null\/NaN/.test(f.title) && /bd = null/.test(f.where)) },
  { name: 'soils.sol: NaN on a later layer line is found too', fw: 'swat_plus',
    files: { 'soils.sol': soils(soil1('S1', 'Loam', '1.4'), soil2.replace('1.5', 'NaN')) },
    expect: r => r.some(f => f.sev === 'error' && /Null\/NaN/.test(f.title)) },
  { name: 'soils.sol: unknown layout -> says nothing (abstains)', fw: 'swat_plus',
    files: { 'soils.sol': 'something else entirely' + NL + 'a b c null d' },
    expect: r => !has(r, /soils\.sol|Null\/NaN/) },
  { name: 'soils.sol: bulk density of zero is a WARNING', fw: 'swat_plus',
    files: { 'soils.sol': soils(soil1('S1', 'Loam', '0.0'), soil2) },
    expect: r => r.some(f => f.sev === 'warning' && /Zero or negative/.test(f.title)) },

  /* ---- periodAlign: MODFLOW time (sum of PERLEN in days) vs the SWAT period ---- */
  { name: 'DIS: one 10,000-day stress period covers a 1-year SWAT run (the real Park model) -> no finding', fw: 'swat_mf',
    files: { 'file.cio': cio(1, 1, 365), 'mf_1000.dis': dis(1, 4, [['1.000000000000E+004', 10000]]) },
    expect: r => !has(r, /MODFLOW time/) },
  { name: 'DIS: 100 days of MODFLOW for a 365-day SWAT run -> ERROR that states both numbers', fw: 'swat_mf',
    files: { 'file.cio': cio(1, 1, 365), 'm.dis': dis(1, 4, [['1.000000000000E+002', 100]]) },
    expect: r => r.some(f => f.sev === 'error' && /MODFLOW time/.test(f.title) && /100 days/.test(f.detail) && /365/.test(f.detail)) },
  { name: 'DIS: several stress periods are summed (3 x 100 d < 5 years -> ERROR; 3 x 800 d >= 5 years -> none)', fw: 'swat_mf',
    files: { 'file.cio': cio(5, 1, 365), 'm.dis': dis(3, 4, [[100, 100], [100, 100], [100, 100]]) },
    expect: r => has(r, /MODFLOW time/) },
  { name: 'DIS: three long periods that add up to enough time -> no finding', fw: 'swat_mf',
    files: { 'file.cio': cio(5, 1, 365), 'm.dis': dis(3, 4, [[800, 800], [800, 800], [800, 800]]) },
    expect: r => !has(r, /MODFLOW time/) },
  { name: 'DIS: time unit in years is converted (10 years >= 5 years -> none; 2 years < 5 -> ERROR)', fw: 'swat_mf',
    files: { 'file.cio': cio(5, 1, 365), 'm.dis': dis(1, 5, [[10, 3650]]) },
    expect: r => !has(r, /MODFLOW time/) },
  { name: 'DIS: time unit undefined (ITMUNI 0) -> abstains', fw: 'swat_mf',
    files: { 'file.cio': cio(5, 1, 365), 'm.dis': dis(1, 0, [[10, 10]]) },
    expect: r => !has(r, /MODFLOW time/) },
  { name: 'DIS: header says 3 periods but only 2 can be read -> abstains rather than guess', fw: 'swat_mf',
    files: { 'file.cio': cio(5, 1, 365), 'm.dis': dis(3, 4, [[1, 1], [1, 1]]) },
    expect: r => !has(r, /MODFLOW time/) },
  { name: 'DIS: Fortran D exponents are read (1.0D+04 days)', fw: 'swat_mf',
    files: { 'file.cio': cio(1, 1, 365), 'm.dis': dis(1, 4, [['1.0D+04', 10000]]) },
    expect: r => !has(r, /MODFLOW time/) },

  /* ---- emptyFiles: only inputs that the control files name ---- */
  { name: 'empty hru.dat that nothing names is normal -> no finding', fw: 'swat2012',
    files: { 'file.cio': cio(1, 1, 365), 'hru.dat': '', 'rch.dat': '' },
    expect: r => !has(r, /Empty/) },
  { name: 'empty climate file named in file.cio is reported', fw: 'swat2012',
    files: { 'file.cio': cio(1, 1, 365) + NL + 'pcp1.pcp           | PCPFILE: precipitation', 'pcp1.pcp': '' },
    expect: r => r.some(f => /Empty/.test(f.title) && /pcp1\.pcp/.test(f.where)) },
  { name: 'empty .hru file named by a .sub file is reported', fw: 'swat2012',
    files: { 'file.cio': cio(1, 1, 365), '000010000.sub': '000010001.hru   | HRUFILE', '000010001.hru': '' },
    expect: r => r.some(f => /Empty/.test(f.title) && /000010001\.hru/.test(f.where)) },
  { name: 'empty .hru file named by a REAL SWAT2012 .sub line (names written back to back, no spaces) is reported', fw: 'swat2012',
    files: { 'file.cio': cio(1, 1, 365), '000010000.sub': '000010001.hru000010001.mgt000010001.sol000010001.chm 000010001.gw             000010001.se', '000010001.sol': '', '000010001.mgt': 'x', '000010001.hru': 'x' },
    expect: r => r.some(f => /Empty/.test(f.title) && /000010001\.sol/.test(f.where)) },
  { name: 'output.pst mentioned only in a description, and the optional cst.cst, are not reported', fw: 'swat2012',
    files: { 'file.cio': cio(1, 1, 365) + NL + 'cst.cst | FCSTFILE: forecast file' + NL + '0 | IPRP: print code for output.pst file', 'output.pst': '', 'cst.cst': '' },
    expect: r => !has(r, /Empty/) },

  /* ---- cliSorted: unsorted station lists silently drop stations (own-log bug #4; seen in three Pekin projects) ---- */
  { name: 'pcp.cli / tmp.cli in sorted order -> no finding', fw: 'swat_plus',
    files: { 'pcp.cli': 'pcp.cli: list' + NL + 'filename' + NL + 'A1.pcp' + NL + 'B2.pcp' + NL + 'C3.pcp', 'tmp.cli': 'tmp.cli: list' + NL + 'filename' + NL + 'A1.tmp' + NL + 'B2.tmp' },
    expect: r => !has(r, /not sorted/) },
  { name: 'pcp.cli out of order -> ERROR that says how many entries are out of place', fw: 'swat_plus',
    files: { 'pcp.cli': 'pcp.cli: list' + NL + 'filename' + NL + 'C3.pcp' + NL + 'A1.pcp' + NL + 'B2.pcp' },
    expect: r => r.some(f => f.sev === 'error' && /not sorted/.test(f.title) && /pcp\.cli: \d+ of 3/.test(f.where)) },
  /* ---- diagLog: the engine admits what it could not read ---- */
  { name: 'diagnostics.out with "file not found (pgage)" lines -> ERROR naming the files', fw: 'swat_plus',
    files: { 'diagnostics.out': ' DIAGNOSTICS.OUT FILE' + NL + ' A1.pcp                  file not found (pgage)' + NL + ' A1.tmp                  file not found (tgage)' + NL + ' (basins_carbon.tes)    file not found' },
    expect: r => r.some(f => f.sev === 'error' && /missing input files/.test(f.title) && /A1\.pcp/.test(f.where) && /2 /.test(f.where)) },
  { name: 'diagnostics.out that only lacks the optional basins_carbon.tes is clean', fw: 'swat_plus',
    files: { 'diagnostics.out': ' DIAGNOSTICS.OUT FILE' + NL + ' (basins_carbon.tes)    file not found' },
    expect: r => !has(r, /missing input files/) },
  { name: 'diagnostics.out where only the placeholders "sim" / "null" were not found (healthy Bailey models) is clean', fw: 'swat_plus',
    files: { 'diagnostics.out': ' DIAGNOSTICS.OUT FILE' + NL + '  sim file not found (petgage)' + NL + '  sim file not found (petgage)' + NL + ' null file not found (x)' },
    expect: r => !has(r, /missing input files/) },
  { name: 'an empty time.sim named by file.cio is an ERROR (SWAT+ crashed with floating divide by zero)', fw: 'swat_plus',
    files: { 'file.cio': 'simulation  time.sim  print.prt  object.prt  object.cnt', 'time.sim': '' },
    expect: r => r.some(f => f.sev === 'error' && /Empty/.test(f.title)) },
  { name: 'swatmf_link.txt missing in a SWAT-MODFLOW folder is an ERROR', fw: 'swat_mf',
    files: { 'modflow.mfn': 'LIST 20 out.lst' + NL, 'file.cio': 'x' },
    expect: r => r.some(f => f.sev === 'error' && /swatmf_link/.test(f.title)) },
  { name: 'an empty APEXCONT.DAT is an ERROR; non-empty APEX control files are clean', fw: 'apex',
    files: { 'APEXCONT.DAT': '', 'APEXRUN.DAT': 'run' + NL, 'APEXFILE.DAT': 'files' + NL },
    expect: r => r.some(f => f.sev === 'error' && /Empty APEX/.test(f.title)) },
  { name: 'APEX control files with content give no APEX finding', fw: 'apex',
    files: { 'APEXCONT.DAT': 'c' + NL, 'APEXRUN.DAT': 'run' + NL, 'APEXFILE.DAT': 'files' + NL },
    expect: r => !r.some(f => /APEX|apexmf/.test(f.title)) },
  { name: 'apexmf.con without apexmf_link.txt is an ERROR; with it, clean', fw: 'apex',
    files: { 'apexmf.con': 'x' + NL },
    expect: r => r.some(f => f.sev === 'error' && /apexmf_link/.test(f.title)) },
  { name: 'apexmf.con with apexmf_link.txt gives no link finding', fw: 'apex',
    files: { 'apexmf.con': 'x' + NL, 'apexmf_link.txt': 'y' + NL },
    expect: r => !r.some(f => /apexmf_link/.test(f.title)) },
  { name: 'weatherRefs no longer claims that SWAT+ aborts (it carries on; verified by running it)', fw: 'swat_plus',
    files: { 'weather-sta.cli': 'weather-sta.cli: x' + NL + 'name wgn pcp tmp' + NL + 's1 w1 A1.pcp A1.tmp' },
    expect: r => r.some(f => /Weather files referenced/.test(f.title) && /does NOT stop/.test(f.detail) && !/aborts while reading/.test(f.detail)) },

  /* ---- SWAT2012 referencedFiles (names are written back to back in .sub files) ---- */
  { name: 'SWAT2012: .hru named in a real-format .sub line but absent -> ERROR', fw: 'swat2012',
    files: { 'file.cio': cio(1, 1, 365), '000010000.sub': '000010001.hru000010001.mgt000010001.sol000010001.chm 000010001.gw', '000010001.mgt': 'x', '000010001.sol': 'x', '000010001.chm': 'x', '000010001.gw': 'x' },
    expect: r => r.some(f => f.sev === 'error' && /not in the folder/.test(f.title) && /000010001\.hru/.test(f.where)) },
  { name: 'SWAT2012: every named file present -> no finding', fw: 'swat2012',
    files: { 'file.cio': cio(1, 1, 365), '000010000.sub': '000010001.hru000010001.mgt000010001.sol000010001.chm 000010001.gw', '000010001.hru': 'x', '000010001.mgt': 'x', '000010001.sol': 'x', '000010001.chm': 'x', '000010001.gw': 'x' },
    expect: r => !has(r, /not in the folder/) },

  /* ---- SWAT-MODFLOW: the .mfn is checked like a name file, but LIST/DATA lines name files MODFLOW WRITES ---- */
  { name: '.mfn names a package file that is missing -> ERROR', fw: 'swat_mf',
    files: { 'file.cio': cio(1, 1, 365), 'modflow.mfn': 'LIST\t5011\tm.lst' + NL + 'DIS\t5012\tm.dis' + NL + 'UPW\t5134\tm.upw', 'm.dis': 'x' },
    expect: r => r.some(f => f.sev === 'error' && /Name file references/.test(f.title) && /m\.upw/.test(f.where)) },
  { name: '.mfn: LIST and DATA files (written by MODFLOW) that do not exist yet are NOT reported', fw: 'swat_mf',
    files: { 'file.cio': cio(1, 1, 365), 'modflow.mfn': 'LIST\t5011\tm.lst' + NL + 'DATA\t5037\tm.fhd' + NL + 'DATA(BINARY)\t5009\tm.cbc' + NL + 'DIS\t5012\tm.dis', 'm.dis': 'x' },
    expect: r => !has(r, /Name file references/) },
  { name: 'MODFLOW .nam: a missing LIST file is no longer reported either (it is an output)', fw: 'modflow',
    files: { 'model.nam': 'LIST 2 model.lst' + NL + 'DIS 11 model.dis', 'model.dis': 'x' },
    expect: r => !has(r, /Name file references/) },

  /* ---- MODFLOW 6: two modest checks ---- */
  { name: 'MODFLOW 6: package file named in a name file but absent -> ERROR', fw: 'modflow6',
    files: { 'mfsim.nam': 'BEGIN timing' + NL + '  TDIS6  s.tdis' + NL + 'END timing' + NL + 'BEGIN models' + NL + '  gwf6  gwf.nam  gwf' + NL + 'END models', 's.tdis': 'x', 'gwf.nam': 'BEGIN packages' + NL + '  DIS6  gwf.dis  dis' + NL + '  NPF6  gwf.npf  npf' + NL + 'END packages', 'gwf.dis': 'x' },
    expect: r => r.some(f => f.sev === 'error' && /MODFLOW 6 name files/.test(f.title) && /gwf\.npf/.test(f.where)) },
  { name: 'MODFLOW 6: everything named exists -> no finding', fw: 'modflow6',
    files: { 'mfsim.nam': 'BEGIN timing' + NL + '  TDIS6  s.tdis' + NL + 'END timing', 's.tdis': 'x' },
    expect: r => !has(r, /MODFLOW 6 name files/) },
  { name: 'MODFLOW 6: NPER 6 but 5 periods defined -> ERROR', fw: 'modflow6',
    files: { 's.tdis': 'BEGIN dimensions' + NL + '  NPER  6' + NL + 'END dimensions' + NL + 'BEGIN perioddata' + NL + ' 1.0 1 1.0' + NL + ' 1.0 1 1.0' + NL + ' 1.0 1 1.0' + NL + ' 1.0 1 1.0' + NL + ' 1.0 1 1.0' + NL + 'END perioddata' },
    expect: r => r.some(f => f.sev === 'error' && /NPER does not match/.test(f.title) && /5 period/.test(f.detail)) },
  { name: 'MODFLOW 6: NPER equal to the periods defined -> no finding', fw: 'modflow6',
    files: { 's.tdis': 'BEGIN dimensions' + NL + '  NPER  2' + NL + 'END dimensions' + NL + 'BEGIN perioddata' + NL + ' 1.0 1 1.0' + NL + ' 1.0 1 1.0' + NL + 'END perioddata' },
    expect: r => !has(r, /NPER does not match/) },

  /* ---- MODFLOW 6: convergence. Listing evidence (certain) and the IMS settings that were reproduced as failures (WARNING) ---- */
  { name: 'MODFLOW 6 listing: premature termination after a convergence failure -> ERROR with the count and the first failed step', fw: 'modflow6',
    files: { 'mfsim.lst': LST_FAIL },
    expect: r => r.some(f => f.sev === 'error' && /solver did not converge/.test(f.title) && f.where === 'mfsim.lst' && /occurred 1 time\(s\)/.test(f.detail) && /stress period 1, time step 1/.test(f.detail) && /stopped early/.test(f.detail)) },
  { name: 'MODFLOW 6 listing: CONTINUE run that ends "Normal termination" but logged 20 failures -> ERROR that says the run continued', fw: 'modflow6',
    files: { 'mfsim.lst': LST_CONT },
    expect: r => r.some(f => f.sev === 'error' && /solver did not converge/.test(f.title) && /occurred 20 time\(s\)/.test(f.detail) && /continue past the failures/.test(f.detail)) },
  { name: 'MODFLOW 6 listing: only "Solution 1 did not converge" lines (run killed before the report) -> ERROR with the counted steps', fw: 'modflow6',
    files: { 'mfsim.lst': LST_CONT.split('WARNING REPORT:')[0] },
    expect: r => r.some(f => f.sev === 'error' && /solver did not converge/.test(f.title) && /occurred 2 time\(s\)/.test(f.detail)) },
  { name: 'MODFLOW 6 listing: a clean run ("Normal termination", no failure) -> no finding', fw: 'modflow6',
    files: { 'mfsim.lst': LST_OK },
    expect: r => !has(r, /did not converge/) },
  { name: 'MODFLOW 6 IMS: OUTER_MAXIMUM 1 on the flow solution -> WARNING, never an error (a model that does not change at all still converges)', fw: 'modflow6',
    files: mf6(ims('nonlinear', 'OUTER_MAXIMUM  1')),
    expect: r => r.some(f => f.sev === 'warning' && /OUTER_MAXIMUM 1/.test(f.title) && f.where === 'gwf.ims') && !r.some(f => f.sev === 'error' && /converge/.test(f.title)) },
  { name: 'MODFLOW 6 IMS: OUTER_MAXIMUM 2 -> silent (converged in every tested model)', fw: 'modflow6',
    files: mf6(ims('nonlinear', 'OUTER_MAXIMUM  2')),
    expect: r => !has(r, /OUTER_MAXIMUM/) },
  { name: 'MODFLOW 6 IMS: OUTER_MAXIMUM 1 on a transport (GWT) solution only -> silent (it converged with zero concentrations)', fw: 'modflow6',
    files: mf6(ims('nonlinear', 'OUTER_MAXIMUM  50'), ims('nonlinear', 'OUTER_MAXIMUM  1')),
    expect: r => !has(r, /OUTER_MAXIMUM/) },
  { name: 'MODFLOW 6 IMS: OUTER_MAXIMUM 1 but no mfsim.nam to say which model the IMS serves -> abstains', fw: 'modflow6',
    files: { 'gwf.ims': ims('nonlinear', 'OUTER_MAXIMUM  1') },
    expect: r => !has(r, /OUTER_MAXIMUM/) },
  { name: 'MODFLOW 6 IMS: OUTER_DVCLOSE 1e-20 (the F03 benchmark case) -> WARNING; the Fortran form 1.0D-16 and the old name OUTER_HCLOSE too', fw: 'modflow6',
    files: mf6(ims('nonlinear', 'OUTER_DVCLOSE  1.0E-20')),
    expect: r => r.some(f => f.sev === 'warning' && /OUTER_DVCLOSE 1\.0E-20/.test(f.title)) && has(mf6r(mf6(ims('nonlinear', 'OUTER_HCLOSE  1.0D-16'))), /OUTER_DVCLOSE 1\.0D-16/) },
  { name: 'MODFLOW 6 IMS: OUTER_DVCLOSE 1e-10 and 1e-6 -> silent (converged in every tested model)', fw: 'modflow6',
    files: mf6(ims('nonlinear', 'OUTER_DVCLOSE  1.0E-10')),
    expect: r => !has(r, /OUTER_DVCLOSE/) && !has(mf6r(mf6(ims('nonlinear', 'OUTER_DVCLOSE  1.0E-6'))), /OUTER_DVCLOSE/) },
  { name: 'MODFLOW 6 IMS: two OUTER_DVCLOSE values (one per model) -> abstains', fw: 'modflow6',
    files: mf6(ims('nonlinear', 'OUTER_DVCLOSE  1.0E-3 1.0E-20')),
    expect: r => !has(r, /OUTER_DVCLOSE/) },
  { name: 'MODFLOW 6 IMS: INNER_RCLOSE 1e-18 -> WARNING; 0.1, and a RELATIVE_RCLOSE option, -> silent', fw: 'modflow6',
    files: mf6(ims('linear', 'INNER_RCLOSE  1.0E-18')),
    expect: r => r.some(f => f.sev === 'warning' && /INNER_RCLOSE/.test(f.title)) && !has(mf6r(mf6(ims('linear', 'INNER_RCLOSE  0.1'))), /INNER_RCLOSE/) && !has(mf6r(mf6(ims('linear', 'INNER_RCLOSE  1.0E-18 RELATIVE_RCLOSE'))), /INNER_RCLOSE/) },
  { name: 'MODFLOW 6 IMS: default solver settings (COMPLEXITY only) -> no solver finding', fw: 'modflow6',
    files: mf6('BEGIN options' + NL + '  COMPLEXITY  moderate' + NL + 'END options' + NL),
    expect: r => !has(r, /IMS|did not converge/) },
];

/* ---- real folders: models that ran must not get an ERROR ---- */
const cfg = require('../bench/config');   // real-folder cases come from the benchmark configuration (bench/hydra_bench.config.example.json)
const unconfigured = cfg.isUnconfigured();
const real = unconfigured ? [] : cfg.getList('rules_real_folders').map(c => [c.name, c.dir]);
/* the Pekin projects ran, but their station lists are unsorted and their own log says ~250 files were not found: the ERROR is a TRUE positive */
const truePositive = unconfigured ? [] : cfg.getList('rules_true_positive_folders').map(c => [c.name, c.dir, new RegExp(c.pattern)]);
if (unconfigured) console.log('SKIP real-folder cases: no benchmark configuration (' + cfg.configFile() + ' does not exist); keys rules_real_folders and rules_true_positive_folders');
const isOutput = (f, size) => size > 1024 * 1024 && /(_day|_mon|_yr|_aa)\.(txt|csv)$|\.out$|\.cbc$|\.hds$|\.hed$/i.test(f) && !/^diagnostics\.out$/i.test(f);

let bad = 0, ran = 0, skipped = 0;
for (const c of cases) {
  ran++;
  const r = runRules(c.files, c.fw, Object.keys(c.files));
  const ok = c.expect(r);
  if (!ok) bad++;
  console.log((ok ? 'PASS ' : 'FAIL ') + c.name + (ok ? '' : '\n      got: ' + JSON.stringify(titles(r))));
}
for (const [name, dir] of real) {
  if (!fs.existsSync(dir)) { skipped++; console.log('SKIP real model (folder absent): ' + name); continue; }
  ran++;
  const full = loadFolderFull(dir, 8 * 1024 * 1024, isOutput);
  const fw = HDA.ruleKeyFor(HDA.characterize(full.entries).systems[0]);
  const r = runRules(full.files, fw, full.filenames);
  const errors = r.filter(f => f.sev === 'error');
  const ok = errors.length === 0;
  if (!ok) bad++;
  console.log((ok ? 'PASS ' : 'FAIL ') + '[real] no ERROR on a model that runs: ' + name + (ok ? '' : '\n      got: ' + JSON.stringify(titles(errors))));
}
for (const [name, dir, re] of truePositive) {
  if (!fs.existsSync(dir)) { skipped++; console.log('SKIP real model (folder absent): ' + name); continue; }
  ran++;
  const full = loadFolderFull(dir, 8 * 1024 * 1024, isOutput);
  const fw = HDA.ruleKeyFor(HDA.characterize(full.entries).systems[0]);
  const r = runRules(full.files, fw, full.filenames);
  const ok = r.some(f => f.sev === 'error' && re.test(f.title));
  if (!ok) bad++;
  console.log((ok ? 'PASS ' : 'FAIL ') + '[real] true positive found: ' + name);
}
console.log('\n' + (ran - bad) + '/' + ran + ' passed' + (skipped ? ', ' + skipped + ' skipped' : ''));
process.exit(bad ? 1 : 0);
