// Generated by bench/snapshot.py from evolution/ledger/ and evolution/milestones.json. Do not edit by hand.
window.EVOLUTION_DATA = {
 "generated_from": "evolution/ledger/*.json and evolution/milestones.json",
 "snapshots": [
  {
   "schema": 1,
   "id": "2026-07-11T0142_initial-release",
   "label": "initial release",
   "version": "",
   "taken_at": "2026-07-11T01:42",
   "kind": "backfill",
   "note": "First public version: a single page that checks SWAT, SWAT-MODFLOW and MODFLOW input files with the original generic rules.",
   "backfill_note": "Rule counts are counted in index.html as committed then. No tests, audit or benchmark existed or were recorded for this state.",
   "git": {
    "commit": "e35bfd0",
    "message": "Initial release: Hydro-Model Diagnostic Assistant",
    "commit_date": "2026-07-11T01:44",
    "branch": "not recorded",
    "dirty": null,
    "in_main": null,
    "source": "commit e35bfd0, read from git history"
   },
   "rules": {
    "status": "counted",
    "source": "index.html at commit e35bfd0",
    "families": {
     "swat_plus": {
      "rules": 5,
      "error_calls": 3,
      "warning_calls": 5,
      "name": "SWAT+"
     },
     "swat2012": {
      "rules": 2,
      "error_calls": 3,
      "warning_calls": 1,
      "name": "SWAT2012"
     },
     "swat_mf": {
      "rules": 3,
      "error_calls": 1,
      "warning_calls": 3,
      "name": "SWAT-MODFLOW"
     },
     "modflow": {
      "rules": 3,
      "error_calls": 2,
      "warning_calls": 3,
      "name": "MODFLOW (NWT/2005)"
     },
     "generic": {
      "rules": 2,
      "error_calls": 0,
      "warning_calls": 2,
      "name": "Generic (any model)"
     }
    },
    "total": 15,
    "error_calls": 9,
    "warning_calls": 14,
    "note": "a rule is a function in a RULES array; error/warning calls are finding('error'|'warning', ...) calls with a literal severity, so a rule can hold several"
   },
   "tests": {
    "status": "not recorded",
    "reason": "past state: tests were not run at that time"
   },
   "audit": {
    "status": "not recorded",
    "reason": "no audit result exists for this point in time"
   },
   "benchmark": {
    "status": "not recorded",
    "reason": "no benchmark result for this point in time"
   },
   "inventory": {
    "status": "not recorded"
   },
   "provenance": {
    "measured_when_taken": [],
    "reconstructed_from_saved_files": [
     "git commit",
     "rule counts"
    ],
    "not_recorded": [
     "benchmark matrix",
     "model inventory",
     "precision audit",
     "test results"
    ]
   }
  },
  {
   "schema": 1,
   "id": "2026-10-08T1635_before-improvements",
   "label": "before improvements",
   "version": "",
   "taken_at": "2026-10-08T16:35",
   "kind": "backfill",
   "note": "First execution of the 22 injected faults (plus 6 unmodified controls) on the real engines, scored against the tool exactly as it was before any rule was changed because of these results.",
   "backfill_note": "Benchmark matrix reconstructed from the saved first-run result file (run and tool answers were written at the time of the run). Which commit this tool state corresponds to was not recorded, so rule counts are not recorded; no tests or audit were saved for this moment.",
   "git": {
    "commit": "not recorded",
    "message": "",
    "commit_date": "",
    "branch": "not recorded",
    "dirty": null,
    "in_main": null,
    "source": "the committed state this snapshot describes was not recorded"
   },
   "rules": {
    "status": "not recorded"
   },
   "tests": {
    "status": "not recorded",
    "reason": "past state: tests were not run at that time"
   },
   "audit": {
    "status": "not recorded",
    "reason": "no audit result exists for this point in time"
   },
   "benchmark": {
    "status": "read",
    "source_file": "results_BEFORE_improvements.json",
    "tool_field": "tool",
    "source_file_time": "2026-10-08T16:35",
    "rescored_now": false,
    "answers_re_asked": 0,
    "answers_from_saved_file": 28,
    "effect_file": "effect.json",
    "fault_cases": 22,
    "controls": 6,
    "control_false_alarms": 0,
    "groups": {
     "stop": {
      "label": "faults that stop the engine",
      "cases": 15,
      "cause_named": 8,
      "as_error": 3
     },
     "silent_damage": {
      "label": "faults the run survives that change results",
      "cases": 4,
      "cause_named": 2,
      "as_error": 2
     },
     "no_effect": {
      "label": "faults the run survives with no effect on results",
      "cases": 2,
      "cause_named": 2,
      "as_error": 0
     }
    },
    "cases": [
     {
      "id": "A01_missing_soil",
      "family": "apex",
      "fault": "HOUSTON.SOL deleted",
      "is_control": false,
      "expected": "crash",
      "engine": "OK",
      "verdict": "ABSTAIN",
      "evidence": "No APEX rules exist yet: this tool identified the model, but only the generic file checks ran.",
      "answer_from": "saved file"
     },
     {
      "id": "A02_empty_apexcont",
      "family": "apex",
      "fault": "APEXCONT.DAT truncated to 0 bytes",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "ABSTAIN",
      "evidence": "No APEX rules exist yet: this tool identified the model, but only the generic file checks ran.",
      "answer_from": "saved file"
     },
     {
      "id": "AM01_link_missing",
      "family": "apexmf",
      "fault": "apexmf_link.txt deleted",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "ABSTAIN",
      "evidence": "No APEX rules exist yet: this tool identified the model, but only the generic file checks ran. The APEX-MODFLOW coupling is not checked yet.",
      "answer_from": "saved file"
     },
     {
      "id": "C_apex",
      "family": "apex",
      "fault": "unmodified base (control)",
      "is_control": true,
      "expected": "ok",
      "engine": "OK",
      "verdict": "ABSTAIN",
      "evidence": "No APEX rules exist yet: this tool identified the model, but only the generic file checks ran.",
      "answer_from": "saved file"
     },
     {
      "id": "C_apexmf",
      "family": "apexmf",
      "fault": "unmodified base (control)",
      "is_control": true,
      "expected": "ok",
      "engine": "OK",
      "verdict": "ABSTAIN",
      "evidence": "No APEX rules exist yet: this tool identified the model, but only the generic file checks ran. The APEX-MODFLOW coupling is not checked yet.",
      "answer_from": "saved file"
     },
     {
      "id": "C_mf6",
      "family": "mf6",
      "fault": "unmodified base (control)",
      "is_control": true,
      "expected": "ok",
      "engine": "OK",
      "verdict": "SILENT",
      "evidence": "No MODFLOW 6 rules exist yet: this tool identified the model, but only the generic file checks ran.",
      "answer_from": "saved file"
     },
     {
      "id": "C_swat2012",
      "family": "swat2012",
      "fault": "unmodified base (control)",
      "is_control": true,
      "expected": "ok",
      "engine": "OK",
      "verdict": "SILENT",
      "evidence": "SWAT2012 rule set.",
      "answer_from": "saved file"
     },
     {
      "id": "C_swatmf",
      "family": "swatmf",
      "fault": "unmodified base (control)",
      "is_control": true,
      "expected": "ok",
      "engine": "OK",
      "verdict": "SILENT",
      "evidence": "SWAT-MODFLOW rule set (linkage, unit numbers, period alignment).",
      "answer_from": "saved file"
     },
     {
      "id": "C_swatplus_p29",
      "family": "swatplus_p29",
      "fault": "unmodified base (control)",
      "is_control": true,
      "expected": "ok",
      "engine": "OK",
      "verdict": "ELSEWHERE",
      "evidence": "warning: gwflow input files exist but the module is switched off (codes.bsn has gwflow = 0).",
      "answer_from": "saved file"
     },
     {
      "id": "F01_tdis_nper_mismatch",
      "family": "mf6",
      "fault": "NPER says 6 periods but 5 are defined",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "SILENT",
      "evidence": "No MODFLOW 6 rules exist yet: this tool identified the model, but only the generic file checks ran.",
      "answer_from": "saved file"
     },
     {
      "id": "F02_missing_npf",
      "family": "mf6",
      "fault": "gwf.npf deleted",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "SILENT",
      "evidence": "No MODFLOW 6 rules exist yet: this tool identified the model, but only the generic file checks ran.",
      "answer_from": "saved file"
     },
     {
      "id": "F03_outer_maximum_one",
      "family": "mf6",
      "fault": "OUTER_MAXIMUM 1 and a tiny closure: cannot converge",
      "is_control": false,
      "expected": "unknown",
      "engine": "BROKE",
      "verdict": "SILENT",
      "evidence": "No MODFLOW 6 rules exist yet: this tool identified the model, but only the generic file checks ran.",
      "answer_from": "saved file"
     },
     {
      "id": "M01_mfn_low_units",
      "family": "swatmf",
      "fault": "low Fortran unit numbers in modflow.mfn",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "WARN",
      "evidence": "warning: Low file-unit numbers in modflow.mfn | DIS → unit 12 (line 5) · BAS6 → unit 13 (line 6) | SWAT-MODFLOW reserves low Fortran unit numbers; conflicts cause silent crashes at startup (period 1, day 1).",
      "answer_from": "saved file"
     },
     {
      "id": "M02_dis_short_perlen",
      "family": "swatmf",
      "fault": "MODFLOW time (sum PERLEN) shorter than the SWAT period",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "ERROR",
      "evidence": "error: MODFLOW time is shorter than the SWAT period | mf_1000.dis | The stress periods in the DIS file add up to 100 days (1 period, PERLEN summed), but SWAT simulates ≈730 days. SWAT-MODFLOW advances MODFLOW one day at a time through the stress …",
      "answer_from": "saved file"
     },
     {
      "id": "M03_link_missing",
      "family": "swatmf",
      "fault": "swatmf_link.txt deleted",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "WARN",
      "evidence": "warning: swatmf_link.txt not found | swatmf_link.txt | The link file controls coupling outputs and options; without it the exchange is not configured.",
      "answer_from": "saved file"
     },
     {
      "id": "M04_package_missing",
      "family": "swatmf",
      "fault": "mf_1000.upw named in modflow.mfn is deleted",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "SILENT",
      "evidence": "SWAT-MODFLOW rule set (linkage, unit numbers, period alignment).",
      "answer_from": "saved file"
     },
     {
      "id": "P02_gwflow_flag_on",
      "family": "swatplus_p29",
      "fault": "codes.bsn gwflow=1 while file.cio connects aquifer.con (gwflow files present)",
      "is_control": false,
      "expected": "unknown",
      "engine": "NO-EFFECT",
      "verdict": "WARN",
      "evidence": "warning: codes.bsn says gwflow = 1 but file.cio does not connect gwflow.con. The two disagree. (+1 more)",
      "answer_from": "saved file"
     },
     {
      "id": "P03_end_before_start",
      "family": "swatplus_p29",
      "fault": "time.sim end year before start year",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "ERROR",
      "evidence": "error: Simulation end date is before the start date | time.sim | Parsed: start day 0, year 2020 → end day 0, year 1999. The model will stop on day 1.",
      "answer_from": "saved file"
     },
     {
      "id": "P04_missing_climate",
      "family": "swatplus_p29",
      "fault": "a precipitation file named in weather-sta.cli is deleted",
      "is_control": false,
      "expected": "crash",
      "engine": "CHANGED",
      "verdict": "ERROR",
      "evidence": "error: Weather files referenced but not found | weather-sta.cli → GHCND_US1TXVV0014.pcp | The station file points to climate files that are not in the folder — the run aborts while reading weather.",
      "answer_from": "saved file"
     },
     {
      "id": "P05_soil_numeric_null",
      "family": "swatplus_p29",
      "fault": "null in a numeric soil column (bd)",
      "is_control": false,
      "expected": "crash",
      "engine": "CHANGED",
      "verdict": "ERROR",
      "evidence": "error: Null/NaN fields inside soils.sol | soils.sol — line 4: bd = null | A numeric soil property holds null or NaN. This is the most common cause of the floating invalid (error 65) crash: the model computes with an undefined number and aborts. (…",
      "answer_from": "saved file"
     },
     {
      "id": "P06_empty_time_sim",
      "family": "swatplus_p29",
      "fault": "time.sim truncated to 0 bytes",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "WARN",
      "evidence": "warning: Empty (0-byte) files that the model reads | time.sim | These files are named as inputs by the control files but contain nothing. An empty input file usually means an interrupted write by the GUI/editor and causes end-of-file crashes.",
      "answer_from": "saved file"
     },
     {
      "id": "P07_unsorted_pcp_cli",
      "family": "swatplus_p29",
      "fault": "stations in pcp.cli no longer sorted",
      "is_control": false,
      "expected": "silent",
      "engine": "CHANGED",
      "verdict": "ELSEWHERE",
      "evidence": "warning: gwflow input files exist but the module is switched off (codes.bsn has gwflow = 0).",
      "answer_from": "saved file"
     },
     {
      "id": "P08_hru_rows_short",
      "family": "swatplus_p29",
      "fault": "hru-data.hru rows lose their last field",
      "is_control": false,
      "expected": "unknown",
      "engine": "CHANGED",
      "verdict": "ELSEWHERE",
      "evidence": "warning: gwflow input files exist but the module is switched off (codes.bsn has gwflow = 0).",
      "answer_from": "saved file"
     },
     {
      "id": "P09_codes_rev62_layout",
      "family": "swatplus_p29",
      "fault": "rev-62 column layout in codes.bsn read by a rev-61 engine",
      "is_control": false,
      "expected": "unknown",
      "engine": "NO-EFFECT",
      "verdict": "WARN",
      "evidence": "warning: gwflow input files exist but the module is switched off (codes.bsn has gwflow = 0). (+1 more)",
      "answer_from": "saved file"
     },
     {
      "id": "W01_nbyr_exceeds_climate",
      "family": "swat2012",
      "fault": "NBYR=60 but the climate record is ~33 years",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "WARN",
      "evidence": "warning: Climate file may not cover the simulation period | pcp1.pcp | file.cio asks for 60 year(s) starting 1980; pcp1.pcp contains 33 year(s) [1980–2012]. A shorter climate record makes SWAT stop or fill with generator data.",
      "answer_from": "saved file"
     },
     {
      "id": "W02_sol_null",
      "family": "swat2012",
      "fault": "null bulk density in a .sol file",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "ERROR",
      "evidence": "error: Null values in soil (.sol) files | 000010001.sol | Null soil properties are a classic cause of runtime crashes and of implausible water-balance output.",
      "answer_from": "saved file"
     },
     {
      "id": "W03_missing_sol",
      "family": "swat2012",
      "fault": "a .sol file named by .sub/.hru is deleted",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "SILENT",
      "evidence": "SWAT2012 rule set.",
      "answer_from": "saved file"
     },
     {
      "id": "W04_empty_sol",
      "family": "swat2012",
      "fault": "a .sol file truncated to 0 bytes",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "WARN",
      "evidence": "warning: Empty (0-byte) files that the model reads | 000010001.sol | These files are named as inputs by the control files but contain nothing. An empty input file usually means an interrupted write by the GUI/editor and causes end-of-file crashes.",
      "answer_from": "saved file"
     }
    ]
   },
   "inventory": {
    "status": "not recorded"
   },
   "provenance": {
    "measured_when_taken": [],
    "reconstructed_from_saved_files": [
     "benchmark matrix (from the saved result file)"
    ],
    "not_recorded": [
     "git commit",
     "model inventory",
     "precision audit",
     "rule counts",
     "test results"
    ]
   }
  },
  {
   "schema": 1,
   "id": "2026-10-08T1729_multi-model-merge",
   "label": "multi-model merge",
   "version": "",
   "taken_at": "2026-10-08T17:29",
   "kind": "backfill",
   "note": "Merge of the multi-model work: the tool identifies the model, version and coupling before checking, with precision-audited rules and new MODFLOW 6 and name-file checks.",
   "backfill_note": "Rule counts are counted in index.html as committed. No test or audit result was saved for this moment (the audit that took false alarms from 138 to 0 is recorded as a milestone from the author's notes).",
   "git": {
    "commit": "3145c5e",
    "message": "Merge multi-model: identify model/version/coupling, precision-audited rules, new checks",
    "commit_date": "2026-10-08T17:29",
    "branch": "not recorded",
    "dirty": null,
    "in_main": null,
    "source": "commit 3145c5e, read from git history"
   },
   "rules": {
    "status": "counted",
    "source": "index.html at commit 3145c5e",
    "families": {
     "swat_plus": {
      "rules": 7,
      "error_calls": 5,
      "warning_calls": 5,
      "name": "SWAT+"
     },
     "swat2012": {
      "rules": 3,
      "error_calls": 4,
      "warning_calls": 1,
      "name": "SWAT2012"
     },
     "swat_mf": {
      "rules": 4,
      "error_calls": 1,
      "warning_calls": 3,
      "name": "SWAT-MODFLOW"
     },
     "modflow": {
      "rules": 3,
      "error_calls": 1,
      "warning_calls": 3,
      "name": "MODFLOW (NWT/2005)"
     },
     "generic": {
      "rules": 2,
      "error_calls": 0,
      "warning_calls": 2,
      "name": "Generic (any model)"
     },
     "modflow6": {
      "rules": 2,
      "error_calls": 2,
      "warning_calls": 0,
      "name": "MODFLOW 6"
     }
    },
    "total": 21,
    "error_calls": 13,
    "warning_calls": 14,
    "note": "a rule is a function in a RULES array; error/warning calls are finding('error'|'warning', ...) calls with a literal severity, so a rule can hold several"
   },
   "tests": {
    "status": "not recorded",
    "reason": "past state: tests were not run at that time"
   },
   "audit": {
    "status": "not recorded",
    "reason": "no audit result exists for this point in time"
   },
   "benchmark": {
    "status": "not recorded",
    "reason": "no benchmark result for this point in time"
   },
   "inventory": {
    "status": "not recorded"
   },
   "provenance": {
    "measured_when_taken": [],
    "reconstructed_from_saved_files": [
     "git commit",
     "rule counts"
    ],
    "not_recorded": [
     "benchmark matrix",
     "model inventory",
     "precision audit",
     "test results"
    ]
   }
  },
  {
   "schema": 1,
   "id": "2026-10-08T2203_after-first-rule-round",
   "label": "after first rule round",
   "version": "",
   "taken_at": "2026-10-08T22:03",
   "kind": "backfill",
   "note": "The improved rules scored again on the same 22 faulted copies (engine outcomes unchanged).",
   "backfill_note": "Benchmark matrix reconstructed from the saved re-scoring file written at this time. The commit is not recorded; the differences from the next snapshot match the rules added in commit 5383737, so this state is the rules just before that commit (inferred, not verified). No rule counts, tests or audit were saved for this moment.",
   "git": {
    "commit": "not recorded",
    "message": "",
    "commit_date": "",
    "branch": "not recorded",
    "dirty": null,
    "in_main": null,
    "source": "the committed state this snapshot describes was not recorded"
   },
   "rules": {
    "status": "not recorded"
   },
   "tests": {
    "status": "not recorded",
    "reason": "past state: tests were not run at that time"
   },
   "audit": {
    "status": "not recorded",
    "reason": "no audit result exists for this point in time"
   },
   "benchmark": {
    "status": "read",
    "source_file": "results_AFTER_prev.json",
    "tool_field": "tool_pre",
    "source_file_time": "2026-10-08T22:03",
    "rescored_now": false,
    "answers_re_asked": 0,
    "answers_from_saved_file": 28,
    "effect_file": "effect.json",
    "fault_cases": 22,
    "controls": 6,
    "control_false_alarms": 0,
    "groups": {
     "stop": {
      "label": "faults that stop the engine",
      "cases": 15,
      "cause_named": 12,
      "as_error": 7
     },
     "silent_damage": {
      "label": "faults the run survives that change results",
      "cases": 4,
      "cause_named": 3,
      "as_error": 3
     },
     "no_effect": {
      "label": "faults the run survives with no effect on results",
      "cases": 2,
      "cause_named": 2,
      "as_error": 0
     }
    },
    "cases": [
     {
      "id": "A01_missing_soil",
      "family": "apex",
      "fault": "HOUSTON.SOL deleted",
      "is_control": false,
      "expected": "crash",
      "engine": "OK",
      "verdict": "ABSTAIN",
      "evidence": "No APEX rules exist yet: this tool identified the model, but only the generic file checks ran.",
      "answer_from": "saved file",
      "verdict_after_run": "ABSTAIN"
     },
     {
      "id": "A02_empty_apexcont",
      "family": "apex",
      "fault": "APEXCONT.DAT truncated to 0 bytes",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "ABSTAIN",
      "evidence": "No APEX rules exist yet: this tool identified the model, but only the generic file checks ran.",
      "answer_from": "saved file",
      "verdict_after_run": "ABSTAIN"
     },
     {
      "id": "AM01_link_missing",
      "family": "apexmf",
      "fault": "apexmf_link.txt deleted",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "ABSTAIN",
      "evidence": "No APEX rules exist yet: this tool identified the model, but only the generic file checks ran. The APEX-MODFLOW coupling is not checked yet.",
      "answer_from": "saved file",
      "verdict_after_run": "ABSTAIN"
     },
     {
      "id": "C_apex",
      "family": "apex",
      "fault": "unmodified base (control)",
      "is_control": true,
      "expected": "ok",
      "engine": "OK",
      "verdict": "ABSTAIN",
      "evidence": "No APEX rules exist yet: this tool identified the model, but only the generic file checks ran.",
      "answer_from": "saved file",
      "verdict_after_run": "ABSTAIN"
     },
     {
      "id": "C_apexmf",
      "family": "apexmf",
      "fault": "unmodified base (control)",
      "is_control": true,
      "expected": "ok",
      "engine": "OK",
      "verdict": "ABSTAIN",
      "evidence": "No APEX rules exist yet: this tool identified the model, but only the generic file checks ran. The APEX-MODFLOW coupling is not checked yet.",
      "answer_from": "saved file",
      "verdict_after_run": "ABSTAIN"
     },
     {
      "id": "C_mf6",
      "family": "mf6",
      "fault": "unmodified base (control)",
      "is_control": true,
      "expected": "ok",
      "engine": "OK",
      "verdict": "SILENT",
      "evidence": "Two MODFLOW 6 checks: that every file named in the name files exists, and that NPER matches the stress periods defined. Nothing else is checked yet (not convergence, not packages, not units).",
      "answer_from": "saved file",
      "verdict_after_run": "SILENT"
     },
     {
      "id": "C_swat2012",
      "family": "swat2012",
      "fault": "unmodified base (control)",
      "is_control": true,
      "expected": "ok",
      "engine": "OK",
      "verdict": "SILENT",
      "evidence": "SWAT2012 rule set.",
      "answer_from": "saved file",
      "verdict_after_run": "SILENT"
     },
     {
      "id": "C_swatmf",
      "family": "swatmf",
      "fault": "unmodified base (control)",
      "is_control": true,
      "expected": "ok",
      "engine": "OK",
      "verdict": "SILENT",
      "evidence": "SWAT-MODFLOW rule set (linkage, unit numbers, period alignment).",
      "answer_from": "saved file",
      "verdict_after_run": "SILENT"
     },
     {
      "id": "C_swatplus_p29",
      "family": "swatplus_p29",
      "fault": "unmodified base (control)",
      "is_control": true,
      "expected": "ok",
      "engine": "OK",
      "verdict": "ELSEWHERE",
      "evidence": "warning: gwflow input files exist but the module is switched off (codes.bsn has gwflow = 0).",
      "answer_from": "saved file",
      "verdict_after_run": "ELSEWHERE"
     },
     {
      "id": "F01_tdis_nper_mismatch",
      "family": "mf6",
      "fault": "NPER says 6 periods but 5 are defined",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "ERROR",
      "evidence": "error: NPER does not match the stress periods defined | mf6swatp_spike.tdis | The dimensions block says NPER = 6 but the perioddata block defines 5 period(s). MODFLOW 6 stops when they disagree (checked by running MODFLOW 6 with NPER changed).",
      "answer_from": "saved file",
      "verdict_after_run": "ERROR"
     },
     {
      "id": "F02_missing_npf",
      "family": "mf6",
      "fault": "gwf.npf deleted",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "ERROR",
      "evidence": "error: MODFLOW 6 name files reference files that are not in the folder | gwf.npf (named in gwf.nam) | MODFLOW 6 stops with an error report as soon as a package file listed in mfsim.nam or a model name file cannot be opened (checked by running MOD…",
      "answer_from": "saved file",
      "verdict_after_run": "ERROR"
     },
     {
      "id": "F03_outer_maximum_one",
      "family": "mf6",
      "fault": "OUTER_MAXIMUM 1 and a tiny closure: cannot converge",
      "is_control": false,
      "expected": "unknown",
      "engine": "BROKE",
      "verdict": "SILENT",
      "evidence": "Two MODFLOW 6 checks: that every file named in the name files exists, and that NPER matches the stress periods defined. Nothing else is checked yet (not convergence, not packages, not units).",
      "answer_from": "saved file",
      "verdict_after_run": "SILENT"
     },
     {
      "id": "M01_mfn_low_units",
      "family": "swatmf",
      "fault": "low Fortran unit numbers in modflow.mfn",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "WARN",
      "evidence": "warning: Low file-unit numbers in modflow.mfn | DIS → unit 12 (line 5) · BAS6 → unit 13 (line 6) | Low Fortran unit numbers can collide with files that SWAT keeps open. Measured on the Middle Bosque model: of 9 values below 5000, 3 stopped the run …",
      "answer_from": "saved file",
      "verdict_after_run": "WARN"
     },
     {
      "id": "M02_dis_short_perlen",
      "family": "swatmf",
      "fault": "MODFLOW time (sum PERLEN) shorter than the SWAT period",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "ERROR",
      "evidence": "error: MODFLOW time is shorter than the SWAT period | mf_1000.dis | The stress periods in the DIS file add up to 100 days (1 period, PERLEN summed), but SWAT simulates ≈730 days. SWAT-MODFLOW advances MODFLOW one day at a time through the stress …",
      "answer_from": "saved file",
      "verdict_after_run": "ERROR"
     },
     {
      "id": "M03_link_missing",
      "family": "swatmf",
      "fault": "swatmf_link.txt deleted",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "WARN",
      "evidence": "warning: swatmf_link.txt not found | swatmf_link.txt | The link file controls coupling outputs and options; without it the exchange is not configured.",
      "answer_from": "saved file",
      "verdict_after_run": "SILENT"
     },
     {
      "id": "M04_package_missing",
      "family": "swatmf",
      "fault": "mf_1000.upw named in modflow.mfn is deleted",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "ERROR",
      "evidence": "error: Name file references files that are not in the folder | modflow.mfn → mf_1000.upw | The name file lists package files that are not in the folder. MODFLOW stops as soon as it cannot open one (checked by running SWAT-MODFLOW with a package f…",
      "answer_from": "saved file",
      "verdict_after_run": "ERROR"
     },
     {
      "id": "P02_gwflow_flag_on",
      "family": "swatplus_p29",
      "fault": "codes.bsn gwflow=1 while file.cio connects aquifer.con (gwflow files present)",
      "is_control": false,
      "expected": "unknown",
      "engine": "NO-EFFECT",
      "verdict": "WARN",
      "evidence": "warning: codes.bsn says gwflow = 1 but file.cio does not connect gwflow.con. The two disagree. (+1 more)",
      "answer_from": "saved file",
      "verdict_after_run": "WARN"
     },
     {
      "id": "P03_end_before_start",
      "family": "swatplus_p29",
      "fault": "time.sim end year before start year",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "ERROR",
      "evidence": "error: Simulation end date is before the start date | time.sim | Parsed: start day 0, year 2020 → end day 0, year 1999. The model will stop on day 1.",
      "answer_from": "saved file",
      "verdict_after_run": "ERROR"
     },
     {
      "id": "P04_missing_climate",
      "family": "swatplus_p29",
      "fault": "a precipitation file named in weather-sta.cli is deleted",
      "is_control": false,
      "expected": "crash",
      "engine": "CHANGED",
      "verdict": "ERROR",
      "evidence": "error: Weather files referenced but not found | weather-sta.cli → GHCND_US1TXVV0014.pcp | The station file points to climate files that are not in the folder. SWAT+ does NOT stop: it writes \"file not found\" in diagnostics.out and carries on witho…",
      "answer_from": "saved file",
      "verdict_after_run": "WARN"
     },
     {
      "id": "P05_soil_numeric_null",
      "family": "swatplus_p29",
      "fault": "null in a numeric soil column (bd)",
      "is_control": false,
      "expected": "crash",
      "engine": "CHANGED",
      "verdict": "ERROR",
      "evidence": "error: Null/NaN fields inside soils.sol | soils.sol — line 4: bd = null | A numeric soil property holds null or NaN. This is the most common cause of the floating invalid (error 65) crash: the model computes with an undefined number and aborts. (…",
      "answer_from": "saved file",
      "verdict_after_run": "ERROR"
     },
     {
      "id": "P06_empty_time_sim",
      "family": "swatplus_p29",
      "fault": "time.sim truncated to 0 bytes",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "WARN",
      "evidence": "warning: Empty (0-byte) files that the model reads | time.sim | These files are named as inputs by the control files but contain nothing. An empty input file usually means an interrupted write by the GUI/editor and causes end-of-file crashes.",
      "answer_from": "saved file",
      "verdict_after_run": "WARN"
     },
     {
      "id": "P07_unsorted_pcp_cli",
      "family": "swatplus_p29",
      "fault": "stations in pcp.cli no longer sorted",
      "is_control": false,
      "expected": "silent",
      "engine": "CHANGED",
      "verdict": "ERROR",
      "evidence": "error: Station lists are not sorted | pcp.cli: 128 of 129 entries out of order | SWAT+ looks each gage up by name assuming the list is sorted. With an unsorted list most stations are reported as \"file not found\" in diagnostics.out and are ignored…",
      "answer_from": "saved file",
      "verdict_after_run": "ERROR"
     },
     {
      "id": "P08_hru_rows_short",
      "family": "swatplus_p29",
      "fault": "hru-data.hru rows lose their last field",
      "is_control": false,
      "expected": "unknown",
      "engine": "CHANGED",
      "verdict": "ELSEWHERE",
      "evidence": "warning: gwflow input files exist but the module is switched off (codes.bsn has gwflow = 0).",
      "answer_from": "saved file",
      "verdict_after_run": "ELSEWHERE"
     },
     {
      "id": "P09_codes_rev62_layout",
      "family": "swatplus_p29",
      "fault": "rev-62 column layout in codes.bsn read by a rev-61 engine",
      "is_control": false,
      "expected": "unknown",
      "engine": "NO-EFFECT",
      "verdict": "WARN",
      "evidence": "warning: gwflow input files exist but the module is switched off (codes.bsn has gwflow = 0). (+1 more)",
      "answer_from": "saved file",
      "verdict_after_run": "WARN"
     },
     {
      "id": "W01_nbyr_exceeds_climate",
      "family": "swat2012",
      "fault": "NBYR=60 but the climate record is ~33 years",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "WARN",
      "evidence": "warning: Climate file may not cover the simulation period | pcp1.pcp | file.cio asks for 60 year(s) starting 1980; pcp1.pcp contains 33 year(s) [1980–2012]. A shorter climate record makes SWAT stop or fill with generator data.",
      "answer_from": "saved file",
      "verdict_after_run": "WARN"
     },
     {
      "id": "W02_sol_null",
      "family": "swat2012",
      "fault": "null bulk density in a .sol file",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "ERROR",
      "evidence": "error: Null values in soil (.sol) files | 000010001.sol | Null soil properties are a classic cause of runtime crashes and of implausible water-balance output.",
      "answer_from": "saved file",
      "verdict_after_run": "ERROR"
     },
     {
      "id": "W03_missing_sol",
      "family": "swat2012",
      "fault": "a .sol file named by .sub/.hru is deleted",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "ERROR",
      "evidence": "error: Input files named by the model are not in the folder | 000010001.sol (named in 000010000.sub) | SWAT2012 stops when it cannot open an input file that a .sub, .hru or fig.fig file names (checked by running SWAT2012 with a .sol file removed).",
      "answer_from": "saved file",
      "verdict_after_run": "WARN"
     },
     {
      "id": "W04_empty_sol",
      "family": "swat2012",
      "fault": "a .sol file truncated to 0 bytes",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "WARN",
      "evidence": "warning: Empty (0-byte) files that the model reads | 000010001.sol | These files are named as inputs by the control files but contain nothing. An empty input file usually means an interrupted write by the GUI/editor and causes end-of-file crashes.",
      "answer_from": "saved file",
      "verdict_after_run": "WARN"
     }
    ]
   },
   "inventory": {
    "status": "not recorded"
   },
   "provenance": {
    "measured_when_taken": [],
    "reconstructed_from_saved_files": [
     "benchmark matrix (from the saved result file)"
    ],
    "not_recorded": [
     "git commit",
     "model inventory",
     "precision audit",
     "rule counts",
     "test results"
    ]
   }
  },
  {
   "schema": 1,
   "id": "2026-10-08T2214_after-empty-sol-and-apex-rules",
   "label": "after empty-sol and APEX rules",
   "version": "",
   "taken_at": "2026-10-08T22:14",
   "kind": "backfill",
   "note": "Empty time.sim and SWAT2012 .sol files are errors, a missing swatmf_link.txt is an error, basic APEX and APEX-MODFLOW checks.",
   "backfill_note": "Rule counts counted in index.html at this commit. Benchmark matrix reconstructed from a saved copy of the re-scoring file written when this commit was made (the copy's file time is later than the original; its content differs from the previous snapshot exactly in the cases these rules target). No test or audit result was saved for this moment.",
   "git": {
    "commit": "5383737",
    "message": "Rules: empty time.sim and SWAT2012 .sol are errors, missing swatmf_link.txt is an error, basic APEX / APEX-MODFLOW checks",
    "commit_date": "2026-10-08T22:14",
    "branch": "not recorded",
    "dirty": null,
    "in_main": null,
    "source": "commit 5383737, read from git history"
   },
   "rules": {
    "status": "counted",
    "source": "index.html at commit 5383737",
    "families": {
     "swat_plus": {
      "rules": 7,
      "error_calls": 5,
      "warning_calls": 5,
      "name": "SWAT+"
     },
     "swat2012": {
      "rules": 3,
      "error_calls": 4,
      "warning_calls": 1,
      "name": "SWAT2012"
     },
     "swat_mf": {
      "rules": 4,
      "error_calls": 2,
      "warning_calls": 2,
      "name": "SWAT-MODFLOW"
     },
     "modflow": {
      "rules": 3,
      "error_calls": 1,
      "warning_calls": 3,
      "name": "MODFLOW (NWT/2005)"
     },
     "generic": {
      "rules": 2,
      "error_calls": 0,
      "warning_calls": 1,
      "name": "Generic (any model)"
     },
     "modflow6": {
      "rules": 2,
      "error_calls": 2,
      "warning_calls": 0,
      "name": "MODFLOW 6"
     },
     "apex": {
      "rules": 2,
      "error_calls": 2,
      "warning_calls": 0,
      "name": "APEX / APEX-MODFLOW"
     }
    },
    "total": 23,
    "error_calls": 16,
    "warning_calls": 12,
    "note": "a rule is a function in a RULES array; error/warning calls are finding('error'|'warning', ...) calls with a literal severity, so a rule can hold several"
   },
   "tests": {
    "status": "not recorded",
    "reason": "past state: tests were not run at that time"
   },
   "audit": {
    "status": "not recorded",
    "reason": "no audit result exists for this point in time"
   },
   "benchmark": {
    "status": "read",
    "source_file": "results_AFTER_round2.json",
    "tool_field": "tool_pre",
    "source_file_time": "2026-10-09T10:17",
    "rescored_now": false,
    "answers_re_asked": 0,
    "answers_from_saved_file": 28,
    "effect_file": "effect.json",
    "fault_cases": 22,
    "controls": 6,
    "control_false_alarms": 0,
    "groups": {
     "stop": {
      "label": "faults that stop the engine",
      "cases": 15,
      "cause_named": 14,
      "as_error": 12
     },
     "silent_damage": {
      "label": "faults the run survives that change results",
      "cases": 4,
      "cause_named": 3,
      "as_error": 3
     },
     "no_effect": {
      "label": "faults the run survives with no effect on results",
      "cases": 2,
      "cause_named": 2,
      "as_error": 0
     }
    },
    "cases": [
     {
      "id": "A01_missing_soil",
      "family": "apex",
      "fault": "HOUSTON.SOL deleted",
      "is_control": false,
      "expected": "crash",
      "engine": "OK",
      "verdict": "SILENT",
      "evidence": "Basic APEX checks only: empty control files (APEXCONT, APEXRUN, APEXFILE) and the APEX-MODFLOW link file. Nothing else in APEX is checked yet.",
      "answer_from": "saved file",
      "verdict_after_run": "SILENT"
     },
     {
      "id": "A02_empty_apexcont",
      "family": "apex",
      "fault": "APEXCONT.DAT truncated to 0 bytes",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "ERROR",
      "evidence": "error: Empty APEX control files | APEXCONT.DAT | APEX reads its control and run-list files at start-up. An empty one stops the run with an end-of-file error (checked by emptying APEXCONT.DAT in a working model).",
      "answer_from": "saved file",
      "verdict_after_run": "ERROR"
     },
     {
      "id": "AM01_link_missing",
      "family": "apexmf",
      "fault": "apexmf_link.txt deleted",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "ERROR",
      "evidence": "error: apexmf_link.txt not found | apexmf_link.txt | This folder has apexmf.con, so it is an APEX-MODFLOW model, and APEX-MODFLOW reads apexmf_link.txt at start-up. Without it the run crashes with an end-of-file error (checked by deleting it from…",
      "answer_from": "saved file",
      "verdict_after_run": "SILENT"
     },
     {
      "id": "C_apex",
      "family": "apex",
      "fault": "unmodified base (control)",
      "is_control": true,
      "expected": "ok",
      "engine": "OK",
      "verdict": "SILENT",
      "evidence": "Basic APEX checks only: empty control files (APEXCONT, APEXRUN, APEXFILE) and the APEX-MODFLOW link file. Nothing else in APEX is checked yet.",
      "answer_from": "saved file",
      "verdict_after_run": "SILENT"
     },
     {
      "id": "C_apexmf",
      "family": "apexmf",
      "fault": "unmodified base (control)",
      "is_control": true,
      "expected": "ok",
      "engine": "OK",
      "verdict": "SILENT",
      "evidence": "Basic APEX checks only: empty control files (APEXCONT, APEXRUN, APEXFILE) and the APEX-MODFLOW link file. Nothing else in APEX is checked yet. The exchange between APEX and MODFLOW is not checked bey…",
      "answer_from": "saved file",
      "verdict_after_run": "SILENT"
     },
     {
      "id": "C_mf6",
      "family": "mf6",
      "fault": "unmodified base (control)",
      "is_control": true,
      "expected": "ok",
      "engine": "OK",
      "verdict": "SILENT",
      "evidence": "Two MODFLOW 6 checks: that every file named in the name files exists, and that NPER matches the stress periods defined. Nothing else is checked yet (not convergence, not packages, not units).",
      "answer_from": "saved file",
      "verdict_after_run": "SILENT"
     },
     {
      "id": "C_swat2012",
      "family": "swat2012",
      "fault": "unmodified base (control)",
      "is_control": true,
      "expected": "ok",
      "engine": "OK",
      "verdict": "SILENT",
      "evidence": "SWAT2012 rule set.",
      "answer_from": "saved file",
      "verdict_after_run": "SILENT"
     },
     {
      "id": "C_swatmf",
      "family": "swatmf",
      "fault": "unmodified base (control)",
      "is_control": true,
      "expected": "ok",
      "engine": "OK",
      "verdict": "SILENT",
      "evidence": "SWAT-MODFLOW rule set (linkage, unit numbers, period alignment).",
      "answer_from": "saved file",
      "verdict_after_run": "SILENT"
     },
     {
      "id": "C_swatplus_p29",
      "family": "swatplus_p29",
      "fault": "unmodified base (control)",
      "is_control": true,
      "expected": "ok",
      "engine": "OK",
      "verdict": "ELSEWHERE",
      "evidence": "warning: gwflow input files exist but the module is switched off (codes.bsn has gwflow = 0).",
      "answer_from": "saved file",
      "verdict_after_run": "ELSEWHERE"
     },
     {
      "id": "F01_tdis_nper_mismatch",
      "family": "mf6",
      "fault": "NPER says 6 periods but 5 are defined",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "ERROR",
      "evidence": "error: NPER does not match the stress periods defined | mf6swatp_spike.tdis | The dimensions block says NPER = 6 but the perioddata block defines 5 period(s). MODFLOW 6 stops when they disagree (checked by running MODFLOW 6 with NPER changed).",
      "answer_from": "saved file",
      "verdict_after_run": "ERROR"
     },
     {
      "id": "F02_missing_npf",
      "family": "mf6",
      "fault": "gwf.npf deleted",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "ERROR",
      "evidence": "error: MODFLOW 6 name files reference files that are not in the folder | gwf.npf (named in gwf.nam) | MODFLOW 6 stops with an error report as soon as a package file listed in mfsim.nam or a model name file cannot be opened (checked by running MOD…",
      "answer_from": "saved file",
      "verdict_after_run": "ERROR"
     },
     {
      "id": "F03_outer_maximum_one",
      "family": "mf6",
      "fault": "OUTER_MAXIMUM 1 and a tiny closure: cannot converge",
      "is_control": false,
      "expected": "unknown",
      "engine": "BROKE",
      "verdict": "SILENT",
      "evidence": "Two MODFLOW 6 checks: that every file named in the name files exists, and that NPER matches the stress periods defined. Nothing else is checked yet (not convergence, not packages, not units).",
      "answer_from": "saved file",
      "verdict_after_run": "SILENT"
     },
     {
      "id": "M01_mfn_low_units",
      "family": "swatmf",
      "fault": "low Fortran unit numbers in modflow.mfn",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "WARN",
      "evidence": "warning: Low file-unit numbers in modflow.mfn | DIS → unit 12 (line 5) · BAS6 → unit 13 (line 6) | Low Fortran unit numbers can collide with files that SWAT keeps open. Measured on the Middle Bosque model: of 9 values below 5000, 3 stopped the run …",
      "answer_from": "saved file",
      "verdict_after_run": "WARN"
     },
     {
      "id": "M02_dis_short_perlen",
      "family": "swatmf",
      "fault": "MODFLOW time (sum PERLEN) shorter than the SWAT period",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "ERROR",
      "evidence": "error: MODFLOW time is shorter than the SWAT period | mf_1000.dis | The stress periods in the DIS file add up to 100 days (1 period, PERLEN summed), but SWAT simulates ≈730 days. SWAT-MODFLOW advances MODFLOW one day at a time through the stress …",
      "answer_from": "saved file",
      "verdict_after_run": "ERROR"
     },
     {
      "id": "M03_link_missing",
      "family": "swatmf",
      "fault": "swatmf_link.txt deleted",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "ERROR",
      "evidence": "error: swatmf_link.txt not found | swatmf_link.txt | SWAT-MODFLOW reads this link file at start-up; without it the run crashes with an end-of-file error (checked by deleting it from a working model).",
      "answer_from": "saved file",
      "verdict_after_run": "SILENT"
     },
     {
      "id": "M04_package_missing",
      "family": "swatmf",
      "fault": "mf_1000.upw named in modflow.mfn is deleted",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "ERROR",
      "evidence": "error: Name file references files that are not in the folder | modflow.mfn → mf_1000.upw | The name file lists package files that are not in the folder. MODFLOW stops as soon as it cannot open one (checked by running SWAT-MODFLOW with a package f…",
      "answer_from": "saved file",
      "verdict_after_run": "ERROR"
     },
     {
      "id": "P02_gwflow_flag_on",
      "family": "swatplus_p29",
      "fault": "codes.bsn gwflow=1 while file.cio connects aquifer.con (gwflow files present)",
      "is_control": false,
      "expected": "unknown",
      "engine": "NO-EFFECT",
      "verdict": "WARN",
      "evidence": "warning: codes.bsn says gwflow = 1 but file.cio does not connect gwflow.con. The two disagree. (+1 more)",
      "answer_from": "saved file",
      "verdict_after_run": "WARN"
     },
     {
      "id": "P03_end_before_start",
      "family": "swatplus_p29",
      "fault": "time.sim end year before start year",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "ERROR",
      "evidence": "error: Simulation end date is before the start date | time.sim | Parsed: start day 0, year 2020 → end day 0, year 1999. The model will stop on day 1.",
      "answer_from": "saved file",
      "verdict_after_run": "ERROR"
     },
     {
      "id": "P04_missing_climate",
      "family": "swatplus_p29",
      "fault": "a precipitation file named in weather-sta.cli is deleted",
      "is_control": false,
      "expected": "crash",
      "engine": "CHANGED",
      "verdict": "ERROR",
      "evidence": "error: Weather files referenced but not found | weather-sta.cli → GHCND_US1TXVV0014.pcp | The station file points to climate files that are not in the folder. SWAT+ does NOT stop: it writes \"file not found\" in diagnostics.out and carries on witho…",
      "answer_from": "saved file",
      "verdict_after_run": "WARN"
     },
     {
      "id": "P05_soil_numeric_null",
      "family": "swatplus_p29",
      "fault": "null in a numeric soil column (bd)",
      "is_control": false,
      "expected": "crash",
      "engine": "CHANGED",
      "verdict": "ERROR",
      "evidence": "error: Null/NaN fields inside soils.sol | soils.sol — line 4: bd = null | A numeric soil property holds null or NaN. Reported often in the community as the cause of the floating invalid (error 65) crash. In one test here (null in the bulk density…",
      "answer_from": "saved file",
      "verdict_after_run": "ERROR"
     },
     {
      "id": "P06_empty_time_sim",
      "family": "swatplus_p29",
      "fault": "time.sim truncated to 0 bytes",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "ERROR",
      "evidence": "error: Empty (0-byte) files that the model reads | time.sim | These files are named as inputs by the control files but contain nothing. An empty input file usually means an interrupted write by the GUI/editor and causes end-of-file crashes. Check…",
      "answer_from": "saved file",
      "verdict_after_run": "ERROR"
     },
     {
      "id": "P07_unsorted_pcp_cli",
      "family": "swatplus_p29",
      "fault": "stations in pcp.cli no longer sorted",
      "is_control": false,
      "expected": "silent",
      "engine": "CHANGED",
      "verdict": "ERROR",
      "evidence": "error: Station lists are not sorted | pcp.cli: 128 of 129 entries out of order | SWAT+ looks each gage up by name assuming the list is sorted. With an unsorted list most stations are reported as \"file not found\" in diagnostics.out and are ignored…",
      "answer_from": "saved file",
      "verdict_after_run": "ERROR"
     },
     {
      "id": "P08_hru_rows_short",
      "family": "swatplus_p29",
      "fault": "hru-data.hru rows lose their last field",
      "is_control": false,
      "expected": "unknown",
      "engine": "CHANGED",
      "verdict": "ELSEWHERE",
      "evidence": "warning: gwflow input files exist but the module is switched off (codes.bsn has gwflow = 0).",
      "answer_from": "saved file",
      "verdict_after_run": "ELSEWHERE"
     },
     {
      "id": "P09_codes_rev62_layout",
      "family": "swatplus_p29",
      "fault": "rev-62 column layout in codes.bsn read by a rev-61 engine",
      "is_control": false,
      "expected": "unknown",
      "engine": "NO-EFFECT",
      "verdict": "WARN",
      "evidence": "warning: gwflow input files exist but the module is switched off (codes.bsn has gwflow = 0). (+1 more)",
      "answer_from": "saved file",
      "verdict_after_run": "WARN"
     },
     {
      "id": "W01_nbyr_exceeds_climate",
      "family": "swat2012",
      "fault": "NBYR=60 but the climate record is ~33 years",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "WARN",
      "evidence": "warning: Climate file may not cover the simulation period | pcp1.pcp | file.cio asks for 60 year(s) starting 1980; pcp1.pcp contains 33 year(s) [1980–2012]. A shorter climate record makes SWAT stop or fill with generator data.",
      "answer_from": "saved file",
      "verdict_after_run": "WARN"
     },
     {
      "id": "W02_sol_null",
      "family": "swat2012",
      "fault": "null bulk density in a .sol file",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "ERROR",
      "evidence": "error: Null values in soil (.sol) files | 000010001.sol | Null soil properties are a classic cause of runtime crashes and of implausible water-balance output.",
      "answer_from": "saved file",
      "verdict_after_run": "ERROR"
     },
     {
      "id": "W03_missing_sol",
      "family": "swat2012",
      "fault": "a .sol file named by .sub/.hru is deleted",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "ERROR",
      "evidence": "error: Input files named by the model are not in the folder | 000010001.sol (named in 000010000.sub) | SWAT2012 stops when it cannot open an input file that a .sub, .hru or fig.fig file names (checked by running SWAT2012 with a .sol file removed).",
      "answer_from": "saved file",
      "verdict_after_run": "ERROR"
     },
     {
      "id": "W04_empty_sol",
      "family": "swat2012",
      "fault": "a .sol file truncated to 0 bytes",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "ERROR",
      "evidence": "error: Empty (0-byte) files that the model reads | 000010001.sol | These files are named as inputs by the control files but contain nothing. An empty input file usually means an interrupted write by the GUI/editor and causes end-of-file crashes. …",
      "answer_from": "saved file",
      "verdict_after_run": "ERROR"
     }
    ]
   },
   "inventory": {
    "status": "not recorded"
   },
   "provenance": {
    "measured_when_taken": [],
    "reconstructed_from_saved_files": [
     "benchmark matrix (from the saved result file)",
     "git commit",
     "rule counts"
    ],
    "not_recorded": [
     "model inventory",
     "precision audit",
     "test results"
    ]
   }
  },
  {
   "schema": 1,
   "id": "2026-10-09T1029_current",
   "label": "current",
   "version": "",
   "taken_at": "2026-10-09T10:29",
   "kind": "live",
   "note": "State after merging the MODFLOW 6 convergence rules, the automatic fixes and the table-rows rule into the working branch (not yet in main). Benchmark answers are the current rules asked again on the saved faulted copies.",
   "backfill_note": "",
   "git": {
    "commit": "e19c3c5",
    "message": "Merge automatic fixes for three findings",
    "commit_date": "2026-10-09T10:17",
    "branch": "multi-model",
    "dirty": true,
    "in_main": false,
    "source": "HEAD of the main checkout when the snapshot was taken"
   },
   "rules": {
    "status": "counted",
    "source": "index.html in the working tree",
    "families": {
     "swat_plus": {
      "rules": 8,
      "error_calls": 5,
      "warning_calls": 5,
      "name": "SWAT+"
     },
     "swat2012": {
      "rules": 3,
      "error_calls": 4,
      "warning_calls": 1,
      "name": "SWAT2012"
     },
     "swat_mf": {
      "rules": 4,
      "error_calls": 2,
      "warning_calls": 2,
      "name": "SWAT-MODFLOW"
     },
     "modflow": {
      "rules": 3,
      "error_calls": 1,
      "warning_calls": 3,
      "name": "MODFLOW (NWT/2005)"
     },
     "generic": {
      "rules": 2,
      "error_calls": 0,
      "warning_calls": 1,
      "name": "Generic (any model)"
     },
     "modflow6": {
      "rules": 4,
      "error_calls": 3,
      "warning_calls": 3,
      "name": "MODFLOW 6"
     },
     "apex": {
      "rules": 2,
      "error_calls": 2,
      "warning_calls": 0,
      "name": "APEX / APEX-MODFLOW"
     }
    },
    "total": 26,
    "error_calls": 17,
    "warning_calls": 15,
    "note": "a rule is a function in a RULES array; error/warning calls are finding('error'|'warning', ...) calls with a literal severity, so a rule can hold several"
   },
   "tests": {
    "suites": {
     "characterization": {
      "status": "run",
      "passed": 37,
      "total": 37,
      "failed": 0,
      "fail_lines": 0
     },
     "rules": {
      "status": "run",
      "passed": 61,
      "total": 61,
      "failed": 0,
      "fail_lines": 0
     },
     "table-rows rule": {
      "status": "run",
      "passed": 6,
      "total": 6,
      "failed": 0,
      "fail_lines": 0
     },
     "automatic fixes": {
      "status": "run",
      "passed": 67,
      "total": 67,
      "failed": 0,
      "fail_lines": 0
     }
    },
    "passed": 171,
    "total": 171,
    "suites_run": 4,
    "status": "run"
   },
   "audit": {
    "status": "read",
    "result_file_time": "2026-10-09T10:12",
    "how": "last saved result of tests/audit_fp.js, read not re-run",
    "models_audited": 156,
    "working": 141,
    "no_success_marker": 15,
    "working_with_error": 8,
    "working_with_warning_or_error": 8,
    "error_findings_on_working": 13,
    "findings_on_working_by_rule": [
     {
      "severity": "error",
      "title": "Station lists are not sorted",
      "working_models": 5
     },
     {
      "severity": "error",
      "title": "The last run reported missing input files",
      "working_models": 5
     },
     {
      "severity": "error",
      "title": "Weather files referenced but not found",
      "working_models": 3
     }
    ],
    "note": "raw count of error findings on models that ran; they are false-alarm candidates and were not re-adjudicated by this script"
   },
   "benchmark": {
    "status": "read",
    "source_file": "results_AFTER.json",
    "tool_field": "tool_pre",
    "source_file_time": "2026-10-09T10:29",
    "rescored_now": true,
    "answers_re_asked": 28,
    "answers_from_saved_file": 0,
    "effect_file": "effect.json",
    "fault_cases": 22,
    "controls": 6,
    "control_false_alarms": 0,
    "groups": {
     "stop": {
      "label": "faults that stop the engine",
      "cases": 15,
      "cause_named": 15,
      "as_error": 12
     },
     "silent_damage": {
      "label": "faults the run survives that change results",
      "cases": 4,
      "cause_named": 4,
      "as_error": 4
     },
     "no_effect": {
      "label": "faults the run survives with no effect on results",
      "cases": 2,
      "cause_named": 2,
      "as_error": 0
     }
    },
    "cases": [
     {
      "id": "A01_missing_soil",
      "family": "apex",
      "fault": "HOUSTON.SOL deleted",
      "is_control": false,
      "expected": "crash",
      "engine": "OK",
      "verdict": "SILENT",
      "evidence": "Basic APEX checks only: empty control files (APEXCONT, APEXRUN, APEXFILE) and the APEX-MODFLOW link file. Nothing else in APEX is checked yet.",
      "answer_from": "current rules, re-asked now",
      "verdict_after_run": "SILENT"
     },
     {
      "id": "A02_empty_apexcont",
      "family": "apex",
      "fault": "APEXCONT.DAT truncated to 0 bytes",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "ERROR",
      "evidence": "error: Empty APEX control files | APEXCONT.DAT | APEX reads its control and run-list files at start-up. An empty one stops the run with an end-of-file error (checked by emptying APEXCONT.DAT in a working model).",
      "answer_from": "current rules, re-asked now",
      "verdict_after_run": "ERROR"
     },
     {
      "id": "AM01_link_missing",
      "family": "apexmf",
      "fault": "apexmf_link.txt deleted",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "ERROR",
      "evidence": "error: apexmf_link.txt not found | apexmf_link.txt | This folder has apexmf.con, so it is an APEX-MODFLOW model, and APEX-MODFLOW reads apexmf_link.txt at start-up. Without it the run crashes with an end-of-file error (checked by deleting it from…",
      "answer_from": "current rules, re-asked now",
      "verdict_after_run": "SILENT"
     },
     {
      "id": "C_apex",
      "family": "apex",
      "fault": "unmodified base (control)",
      "is_control": true,
      "expected": "ok",
      "engine": "OK",
      "verdict": "SILENT",
      "evidence": "Basic APEX checks only: empty control files (APEXCONT, APEXRUN, APEXFILE) and the APEX-MODFLOW link file. Nothing else in APEX is checked yet.",
      "answer_from": "current rules, re-asked now",
      "verdict_after_run": "SILENT"
     },
     {
      "id": "C_apexmf",
      "family": "apexmf",
      "fault": "unmodified base (control)",
      "is_control": true,
      "expected": "ok",
      "engine": "OK",
      "verdict": "SILENT",
      "evidence": "Basic APEX checks only: empty control files (APEXCONT, APEXRUN, APEXFILE) and the APEX-MODFLOW link file. Nothing else in APEX is checked yet. The exchange between APEX and MODFLOW is not checked bey…",
      "answer_from": "current rules, re-asked now",
      "verdict_after_run": "SILENT"
     },
     {
      "id": "C_mf6",
      "family": "mf6",
      "fault": "unmodified base (control)",
      "is_control": true,
      "expected": "ok",
      "engine": "OK",
      "verdict": "SILENT",
      "evidence": "Six MODFLOW 6 checks: that every file named in the name files exists, that NPER matches the stress periods defined, whether a listing in the folder (mfsim.lst) records a convergence failure, and thre…",
      "answer_from": "current rules, re-asked now",
      "verdict_after_run": "SILENT"
     },
     {
      "id": "C_swat2012",
      "family": "swat2012",
      "fault": "unmodified base (control)",
      "is_control": true,
      "expected": "ok",
      "engine": "OK",
      "verdict": "SILENT",
      "evidence": "SWAT2012 rule set.",
      "answer_from": "current rules, re-asked now",
      "verdict_after_run": "SILENT"
     },
     {
      "id": "C_swatmf",
      "family": "swatmf",
      "fault": "unmodified base (control)",
      "is_control": true,
      "expected": "ok",
      "engine": "OK",
      "verdict": "SILENT",
      "evidence": "SWAT-MODFLOW rule set (linkage, unit numbers, period alignment).",
      "answer_from": "current rules, re-asked now",
      "verdict_after_run": "SILENT"
     },
     {
      "id": "C_swatplus_p29",
      "family": "swatplus_p29",
      "fault": "unmodified base (control)",
      "is_control": true,
      "expected": "ok",
      "engine": "OK",
      "verdict": "ELSEWHERE",
      "evidence": "warning: gwflow input files exist but the module is switched off (codes.bsn has gwflow = 0).",
      "answer_from": "current rules, re-asked now",
      "verdict_after_run": "ELSEWHERE"
     },
     {
      "id": "F01_tdis_nper_mismatch",
      "family": "mf6",
      "fault": "NPER says 6 periods but 5 are defined",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "ERROR",
      "evidence": "error: NPER does not match the stress periods defined | mf6swatp_spike.tdis | The dimensions block says NPER = 6 but the perioddata block defines 5 period(s). MODFLOW 6 stops when they disagree (checked by running MODFLOW 6 with NPER changed).",
      "answer_from": "current rules, re-asked now",
      "verdict_after_run": "ERROR"
     },
     {
      "id": "F02_missing_npf",
      "family": "mf6",
      "fault": "gwf.npf deleted",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "ERROR",
      "evidence": "error: MODFLOW 6 name files reference files that are not in the folder | gwf.npf (named in gwf.nam) | MODFLOW 6 stops with an error report as soon as a package file listed in mfsim.nam or a model name file cannot be opened (checked by running MOD…",
      "answer_from": "current rules, re-asked now",
      "verdict_after_run": "ERROR"
     },
     {
      "id": "F03_outer_maximum_one",
      "family": "mf6",
      "fault": "OUTER_MAXIMUM 1 and a tiny closure: cannot converge",
      "is_control": false,
      "expected": "unknown",
      "engine": "BROKE",
      "verdict": "WARN",
      "evidence": "warning: IMS allows only 1 outer iteration (OUTER_MAXIMUM 1) | gwf.ims | With OUTER_MAXIMUM 1 the solver gets a single outer iteration per time step. In MODFLOW 6.7.0 test runs this stopped with “Simulation convergence failure” in every groundwater… (+1 more)",
      "answer_from": "current rules, re-asked now",
      "verdict_after_run": "ERROR"
     },
     {
      "id": "M01_mfn_low_units",
      "family": "swatmf",
      "fault": "low Fortran unit numbers in modflow.mfn",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "WARN",
      "evidence": "warning: Low file-unit numbers in modflow.mfn | DIS → unit 12 (line 5) · BAS6 → unit 13 (line 6) | Low Fortran unit numbers can collide with files that SWAT keeps open. Measured on the Middle Bosque model: of 9 values below 5000, 3 stopped the run …",
      "answer_from": "current rules, re-asked now",
      "verdict_after_run": "WARN"
     },
     {
      "id": "M02_dis_short_perlen",
      "family": "swatmf",
      "fault": "MODFLOW time (sum PERLEN) shorter than the SWAT period",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "ERROR",
      "evidence": "error: MODFLOW time is shorter than the SWAT period | mf_1000.dis | The stress periods in the DIS file add up to 100 days (1 period, PERLEN summed), but SWAT simulates ≈730 days. SWAT-MODFLOW advances MODFLOW one day at a time through the stress …",
      "answer_from": "current rules, re-asked now",
      "verdict_after_run": "ERROR"
     },
     {
      "id": "M03_link_missing",
      "family": "swatmf",
      "fault": "swatmf_link.txt deleted",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "ERROR",
      "evidence": "error: swatmf_link.txt not found | swatmf_link.txt | SWAT-MODFLOW reads this link file at start-up; without it the run crashes with an end-of-file error (checked by deleting it from a working model).",
      "answer_from": "current rules, re-asked now",
      "verdict_after_run": "SILENT"
     },
     {
      "id": "M04_package_missing",
      "family": "swatmf",
      "fault": "mf_1000.upw named in modflow.mfn is deleted",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "ERROR",
      "evidence": "error: Name file references files that are not in the folder | modflow.mfn → mf_1000.upw | The name file lists package files that are not in the folder. MODFLOW stops as soon as it cannot open one (checked by running SWAT-MODFLOW with a package f…",
      "answer_from": "current rules, re-asked now",
      "verdict_after_run": "ERROR"
     },
     {
      "id": "P02_gwflow_flag_on",
      "family": "swatplus_p29",
      "fault": "codes.bsn gwflow=1 while file.cio connects aquifer.con (gwflow files present)",
      "is_control": false,
      "expected": "unknown",
      "engine": "NO-EFFECT",
      "verdict": "WARN",
      "evidence": "warning: codes.bsn says gwflow = 1 but file.cio does not connect gwflow.con. The two disagree. (+1 more)",
      "answer_from": "current rules, re-asked now",
      "verdict_after_run": "WARN"
     },
     {
      "id": "P03_end_before_start",
      "family": "swatplus_p29",
      "fault": "time.sim end year before start year",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "ERROR",
      "evidence": "error: Simulation end date is before the start date | time.sim | Parsed: start day 0, year 2020 → end day 0, year 1999. The model will stop on day 1.",
      "answer_from": "current rules, re-asked now",
      "verdict_after_run": "ERROR"
     },
     {
      "id": "P04_missing_climate",
      "family": "swatplus_p29",
      "fault": "a precipitation file named in weather-sta.cli is deleted",
      "is_control": false,
      "expected": "crash",
      "engine": "CHANGED",
      "verdict": "ERROR",
      "evidence": "error: Weather files referenced but not found | weather-sta.cli → GHCND_US1TXVV0014.pcp | The station file points to climate files that are not in the folder. SWAT+ does NOT stop: it writes \"file not found\" in diagnostics.out and carries on witho…",
      "answer_from": "current rules, re-asked now",
      "verdict_after_run": "WARN"
     },
     {
      "id": "P05_soil_numeric_null",
      "family": "swatplus_p29",
      "fault": "null in a numeric soil column (bd)",
      "is_control": false,
      "expected": "crash",
      "engine": "CHANGED",
      "verdict": "ERROR",
      "evidence": "error: Null/NaN fields inside soils.sol | soils.sol — line 4: bd = null | A numeric soil property holds null or NaN. Reported often in the community as the cause of the floating invalid (error 65) crash. In one test here (null in the bulk density…",
      "answer_from": "current rules, re-asked now",
      "verdict_after_run": "ERROR"
     },
     {
      "id": "P06_empty_time_sim",
      "family": "swatplus_p29",
      "fault": "time.sim truncated to 0 bytes",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "ERROR",
      "evidence": "error: Empty (0-byte) files that the model reads | time.sim | These files are named as inputs by the control files but contain nothing. An empty input file usually means an interrupted write by the GUI/editor and causes end-of-file crashes. Check…",
      "answer_from": "current rules, re-asked now",
      "verdict_after_run": "ERROR"
     },
     {
      "id": "P07_unsorted_pcp_cli",
      "family": "swatplus_p29",
      "fault": "stations in pcp.cli no longer sorted",
      "is_control": false,
      "expected": "silent",
      "engine": "CHANGED",
      "verdict": "ERROR",
      "evidence": "error: Station lists are not sorted | pcp.cli: 128 of 129 entries out of order | SWAT+ looks each gage up by name assuming the list is sorted. With an unsorted list most stations are reported as \"file not found\" in diagnostics.out and are ignored…",
      "answer_from": "current rules, re-asked now",
      "verdict_after_run": "ERROR"
     },
     {
      "id": "P08_hru_rows_short",
      "family": "swatplus_p29",
      "fault": "hru-data.hru rows lose their last field",
      "is_control": false,
      "expected": "unknown",
      "engine": "CHANGED",
      "verdict": "ERROR",
      "evidence": "error: Rows with a different number of fields than the header | hru-data.hru: 29644 of 29644 rows (line 3 has 9 fields, the header has 10) | SWAT+ reads each row by position. A row with fewer or more fields than the header column list is read shi…",
      "answer_from": "current rules, re-asked now",
      "verdict_after_run": "ERROR"
     },
     {
      "id": "P09_codes_rev62_layout",
      "family": "swatplus_p29",
      "fault": "rev-62 column layout in codes.bsn read by a rev-61 engine",
      "is_control": false,
      "expected": "unknown",
      "engine": "NO-EFFECT",
      "verdict": "WARN",
      "evidence": "warning: gwflow input files exist but the module is switched off (codes.bsn has gwflow = 0). (+1 more)",
      "answer_from": "current rules, re-asked now",
      "verdict_after_run": "WARN"
     },
     {
      "id": "W01_nbyr_exceeds_climate",
      "family": "swat2012",
      "fault": "NBYR=60 but the climate record is ~33 years",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "WARN",
      "evidence": "warning: Climate file may not cover the simulation period | pcp1.pcp | file.cio asks for 60 year(s) starting 1980; pcp1.pcp contains 33 year(s) [1980–2012]. A shorter climate record makes SWAT stop or fill with generator data.",
      "answer_from": "current rules, re-asked now",
      "verdict_after_run": "WARN"
     },
     {
      "id": "W02_sol_null",
      "family": "swat2012",
      "fault": "null bulk density in a .sol file",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "ERROR",
      "evidence": "error: Null values in soil (.sol) files | 000010001.sol | Null soil properties are a classic cause of runtime crashes and of implausible water-balance output.",
      "answer_from": "current rules, re-asked now",
      "verdict_after_run": "ERROR"
     },
     {
      "id": "W03_missing_sol",
      "family": "swat2012",
      "fault": "a .sol file named by .sub/.hru is deleted",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "ERROR",
      "evidence": "error: Input files named by the model are not in the folder | 000010001.sol (named in 000010000.sub) | SWAT2012 stops when it cannot open an input file that a .sub, .hru or fig.fig file names (checked by running SWAT2012 with a .sol file removed).",
      "answer_from": "current rules, re-asked now",
      "verdict_after_run": "ERROR"
     },
     {
      "id": "W04_empty_sol",
      "family": "swat2012",
      "fault": "a .sol file truncated to 0 bytes",
      "is_control": false,
      "expected": "crash",
      "engine": "BROKE",
      "verdict": "ERROR",
      "evidence": "error: Empty (0-byte) files that the model reads | 000010001.sol | These files are named as inputs by the control files but contain nothing. An empty input file usually means an interrupted write by the GUI/editor and causes end-of-file crashes. …",
      "answer_from": "current rules, re-asked now",
      "verdict_after_run": "ERROR"
     }
    ]
   },
   "inventory": {
    "status": "read",
    "folders_audited": 156,
    "by_collection": {
     "Pecos variants": 145,
     "Tutorial": 3,
     "Pekin": 3,
     "Bailey (published)": 2,
     "Park (reference)": 3
    },
    "by_family": {
     "SWAT+": 153,
     "SWAT-MODFLOW": 2,
     "SWAT2012": 1
    },
    "by_coupling": {
     "swatplus-lumped": 6,
     "swatplus-gwflow": 145,
     "swatplus-modflow-nwt": 2,
     "swat-modflow": 2,
     "swat2012-lumped": 1
    },
    "note": "folders are named by collection and family only; no folder names or paths are stored"
   },
   "provenance": {
    "measured_when_taken": [
     "benchmark matrix (from the saved result file)",
     "git commit",
     "model inventory",
     "precision audit (last saved result)",
     "rule counts",
     "test results"
    ],
    "reconstructed_from_saved_files": [],
    "not_recorded": []
   }
  }
 ],
 "milestones": [
  {
   "id": "first-release",
   "date": "2026-07-11",
   "time": "01:42",
   "title": "First public version",
   "description": "A single web page that reads SWAT, SWAT-MODFLOW and MODFLOW input files in the browser and lists likely problems before a run. It had 15 rules and no tests, no audit and no benchmark.",
   "category": "publication",
   "commits": [
    "e35bfd0"
   ],
   "evidence": [
    "snapshot 2026-07-11T0142_initial-release (rule counts read from git history)"
   ],
   "source": "git commit e35bfd0",
   "git_state": {
    "in_working_branch": true,
    "in_published_branch": true,
    "checked": "2026-10-09T10:32"
   }
  },
  {
   "id": "benchmark-first-run",
   "date": "2026-10-08",
   "time": "16:35",
   "title": "Injected-fault benchmark: first execution (22 faults)",
   "description": "22 realistic faults (deleted, truncated or inconsistent input files) were injected into copies of six working models, one per engine, and every copy was run on the real engine. The tool, exactly as it was, was asked about each copy before the run. Of the 15 faults that stop the engine it named the cause in 8, as an error in 3. Of the 4 faults that run to the end but silently change results it named 2.",
   "category": "benchmark",
   "evidence": [
    "snapshot 2026-10-08T1635_before-improvements",
    "results_BEFORE_improvements.json",
    "bench/README.md"
   ],
   "source": "saved result files (written at the time of the run); numbers match the author's notes",
   "metrics": {
    "stop_named": 8,
    "stop_cases": 15,
    "stop_as_error": 3,
    "silent_named": 2,
    "silent_cases": 4
   }
  },
  {
   "id": "effect-probe",
   "date": "2026-10-08",
   "time": "17:02",
   "title": "Silent faults measured: which ones change the results",
   "description": "For the SWAT+ faults the engine survives, the basin water balance was compared with the working model. Four faults (missing climate file, null in a soil column, unsorted climate stations, short rows in hru-data.hru) change the results without any error from the engine. Two (gwflow flag, rev-62 column layout) change nothing.",
   "category": "benchmark",
   "evidence": [
    "snapshot 2026-10-08T1635_before-improvements (engine column: CHANGED / NO-EFFECT)",
    "effect.json"
   ],
   "source": "saved result files (effect probe)"
  },
  {
   "id": "audit-first",
   "date": "2026-10-08",
   "title": "First false-alarm audit: 138 false errors on 141 working models",
   "description": "The rules were run on 141 real models that are known to work (they ran to completion, or are published reference models). A model that works should get no error, so every error there is a false alarm. The first audit found 138.",
   "category": "audit",
   "evidence": [
    "tests/audit_fp.js",
    "git commit message of d0358d2"
   ],
   "source": "git commit d0358d2 and author notes (the time of the first audit run was not recorded)",
   "metrics": {
    "audit_false_alarms": 138,
    "audit_working_models": 141
   }
  },
  {
   "id": "characterization",
   "date": "2026-10-08",
   "time": "17:20",
   "title": "Model characterization and multi-model detection",
   "description": "Before any rule runs, the tool now identifies which model it was given, its version and its coupling: SWAT2012, SWAT+ (rev 61, 62 and older formats), SWAT-MODFLOW, SWAT+MODFLOW, MODFLOW 6, APEX and APEX-MODFLOW. It never falls back to a guess without saying so, and then picks the rule set of the family it identified.",
   "category": "characterization",
   "commits": [
    "d0358d2",
    "3145c5e"
   ],
   "evidence": [
    "snapshot 2026-10-08T1729_multi-model-merge (21 rules in 6 families)",
    "tests/run_node.js (characterization suite, see the latest snapshot for its count)"
   ],
   "source": "git commit d0358d2",
   "git_state": {
    "in_working_branch": true,
    "in_published_branch": true,
    "checked": "2026-10-09T10:32"
   }
  },
  {
   "id": "audit-fixed",
   "date": "2026-10-08",
   "time": "17:20",
   "title": "Rules corrected until no false alarm remained (138 to 0)",
   "description": "Each rule that fired on a working model was corrected or narrowed until none of the 141 working models received a false error. The commit message records the result: false errors went from 138 to 0. The individual rule changes are in that commit; this ledger does not list them one by one.",
   "category": "audit",
   "commits": [
    "d0358d2"
   ],
   "evidence": [
    "git commit d0358d2",
    "tests/audit_fp.js and tests/audit_result.json (last saved audit, see the latest snapshot)"
   ],
   "source": "git commit d0358d2",
   "metrics": {
    "audit_false_alarms": 0,
    "audit_working_models": 141
   },
   "correction": {
    "fixed": "Rules that raised an error on models that run fine.",
    "measured_reason": "Audit on 141 working models: false errors 138 before the fixes, 0 after (commit message of d0358d2)."
   },
   "git_state": {
    "in_working_branch": true,
    "in_published_branch": true,
    "checked": "2026-10-09T10:32"
   }
  },
  {
   "id": "publication-multi-model",
   "date": "2026-10-08",
   "time": "17:29",
   "title": "Publication of the multi-model version",
   "description": "The multi-model version (characterization, audited rules, MODFLOW 6 and name-file checks, updated cover text and README) was merged into main, the branch the project page is built from.",
   "category": "publication",
   "commits": [
    "3145c5e"
   ],
   "evidence": [
    "git commit 3145c5e",
    "snapshot 2026-10-08T1729_multi-model-merge"
   ],
   "source": "git commit 3145c5e",
   "git_state": {
    "in_working_branch": true,
    "in_published_branch": true,
    "checked": "2026-10-09T10:32"
   }
  },
  {
   "id": "header-redesign",
   "date": "2026-10-08",
   "time": "17:49",
   "title": "Header redesign",
   "description": "The header now shows what the tool recognizes, grouped by surface and groundwater models on the left and couplings on the right, with SWAT+ and gwflow listed and the versions it reads.",
   "category": "design",
   "commits": [
    "26fb4e1",
    "e59885b"
   ],
   "evidence": [
    "git commits 26fb4e1 and e59885b"
   ],
   "source": "git commits 26fb4e1 (17:36) and e59885b (17:49)",
   "git_state": {
    "in_working_branch": true,
    "in_published_branch": true,
    "checked": "2026-10-09T10:32"
   }
  },
  {
   "id": "rename",
   "date": "2026-10-08",
   "time": "21:46",
   "title": "Renamed Hydra Check",
   "description": "The tool became Hydra Check, with a tagline and the planned Hydra family of tools, and its project links were pointed to the renamed repository.",
   "category": "design",
   "commits": [
    "95d2fb3",
    "96b1891"
   ],
   "evidence": [
    "git commits 95d2fb3 (21:46) and 96b1891 (21:49)"
   ],
   "source": "git commits 95d2fb3 and 96b1891",
   "git_state": {
    "in_working_branch": true,
    "in_published_branch": true,
    "checked": "2026-10-09T10:32"
   }
  },
  {
   "id": "rules-first-round",
   "date": "2026-10-08",
   "time": "22:03",
   "title": "First rule round after the benchmark: 8 to 12 of 15",
   "description": "Rules were added or tightened for the failures the first run exposed: a stress-period count that does not match, a missing package or .sol file named by a control file, unsorted climate stations. Scored again on the same faulted copies, the tool named the cause of 12 of the 15 engine-stopping faults (7 as an error) and 3 of the 4 silent ones.",
   "category": "rules",
   "evidence": [
    "snapshot 2026-10-08T2203_after-first-rule-round",
    "results_AFTER_prev.json"
   ],
   "source": "saved re-scoring file; the commit of this state was not recorded",
   "metrics": {
    "stop_named": 12,
    "stop_cases": 15,
    "stop_as_error": 7,
    "silent_named": 3,
    "silent_cases": 4
   },
   "correction": {
    "fixed": "Cases that were SILENT or only mentioned elsewhere before: tdis NPER mismatch, gwf.npf deleted, mf_1000.upw deleted, .sol file deleted, unsorted pcp.cli.",
    "measured_reason": "Benchmark verdict changed from SILENT/ELSEWHERE to ERROR on those five cases (see the matrix, columns 1 and 2)."
   }
  },
  {
   "id": "rules-empty-sol-apex",
   "date": "2026-10-08",
   "time": "22:14",
   "title": "Rules for empty time.sim / .sol, missing swatmf_link.txt and basic APEX checks",
   "description": "An empty time.sim or SWAT2012 .sol is an error, a missing swatmf_link.txt is an error, and APEX and APEX-MODFLOW get their first checks (empty control files and the link file). Scored again: the cause of 14 of the 15 engine-stopping faults is named (12 as an error) and 3 of the 4 silent faults.",
   "category": "rules",
   "commits": [
    "5383737"
   ],
   "evidence": [
    "snapshot 2026-10-08T2214_after-empty-sol-and-apex-rules",
    "results_AFTER_round2.json (saved copy of the 22:14 re-scoring)"
   ],
   "source": "git commit 5383737 and saved re-scoring file",
   "metrics": {
    "stop_named": 14,
    "stop_cases": 15,
    "stop_as_error": 12,
    "silent_named": 3,
    "silent_cases": 4
   },
   "correction": {
    "fixed": "Empty time.sim, empty .sol and missing swatmf_link.txt were only a warning or an abstention; APEX had no rules at all.",
    "measured_reason": "Benchmark verdict changed to ERROR on P06, W04, M03, A02 and AM01 (matrix, columns 2 and 3)."
   },
   "git_state": {
    "in_working_branch": true,
    "in_published_branch": true,
    "checked": "2026-10-09T10:32"
   }
  },
  {
   "id": "benchmark-before-after",
   "date": "2026-10-08",
   "time": "22:14",
   "title": "Before / after scores on the 22 faults",
   "description": "Faults that stop the engine and whose cause the tool names: 8 of 15 before, 14 of 15 after. As an error: 3 of 15 before, 12 of 15 after. Faults that run to the end but silently change results: 2 of 4 before, 3 of 4 after. The unmodified controls raised no false error in either.",
   "category": "benchmark",
   "evidence": [
    "snapshots 2026-10-08T1635 and 2026-10-08T2214 (matrix, first and last column)",
    "bench/compare.py"
   ],
   "source": "saved result files; numbers match the author's notes",
   "metrics": {
    "stop_named": 14,
    "stop_cases": 15,
    "stop_as_error": 12,
    "silent_named": 3,
    "silent_cases": 4
   }
  },
  {
   "id": "mf6-convergence",
   "date": "2026-10-09",
   "time": "10:07",
   "title": "MODFLOW 6 convergence rules",
   "description": "An error when the simulation listing records a convergence failure (including runs that still end with a normal termination), and a warning for solver settings that failed in every tested non-degenerate case. According to the measurement notes of this work, the listing rule agreed with 169 of 169 real listings; that figure is quoted from the notes, not re-measured here. In the benchmark this names the last engine-stopping fault that was still unnamed (OUTER_MAXIMUM 1), as a warning.",
   "category": "rules",
   "commits": [
    "cc106c5",
    "fa5bbf8"
   ],
   "evidence": [
    "git commit cc106c5",
    "tests/run_rules_node.js",
    "snapshot 2026-10-09T1029_current (case F03_outer_maximum_one: SILENT before, WARN now)"
   ],
   "source": "git commit cc106c5 and its measurement notes",
   "correction": {
    "fixed": "A fault that stops MODFLOW 6 (OUTER_MAXIMUM 1 with a tiny closure) and that the tool did not mention at all (F03).",
    "measured_reason": "Benchmark verdict changed from SILENT to WARN on F03_outer_maximum_one; the engine stops with a convergence failure on that case."
   },
   "git_state": {
    "in_working_branch": true,
    "in_published_branch": true,
    "checked": "2026-10-09T10:32"
   }
  },
  {
   "id": "autofix",
   "date": "2026-10-09",
   "time": "10:09",
   "title": "Download a fixed file for three findings",
   "description": "For three findings that have a safe mechanical correction (unsorted station list, short MODFLOW period length, low unit numbers in modflow.mfn) the report offers a corrected file to download.",
   "category": "tooling",
   "commits": [
    "177c659",
    "e19c3c5"
   ],
   "evidence": [
    "git commit 177c659",
    "tests/run_fix_node.js (see the latest snapshot for its count)"
   ],
   "source": "git commit 177c659",
   "git_state": {
    "in_working_branch": true,
    "in_published_branch": true,
    "checked": "2026-10-09T10:32"
   }
  },
  {
   "id": "audit-read-cap",
   "date": "2026-10-09",
   "time": "10:12",
   "title": "Audit harness read cap set to the page's own limit (8 MB to 40 MB)",
   "description": "The new rule for rows with a different number of fields than the header fired wrongly on one truncated 12 MB file when the audit read files up to 8 MB. The audit was rerun with the 40 MB limit the page itself applies, and the rule then raised no false alarm on any of the 141 working models. This corrects the audit harness, not a rule.",
   "category": "audit",
   "evidence": [
    "tests/audit_fp.js (read cap)",
    "snapshot 2026-10-09T1029_current (no finding of this rule on the working models in the audit it read)"
   ],
   "source": "integration note from the session that merged the branches; the absence of the finding is checked in the snapshot",
   "correction": {
    "fixed": "The audit measured the new table-rows rule with a smaller file-size cap than the page uses, so one truncated file looked like a false alarm.",
    "measured_reason": "With the page's own 40 MB cap, 141 working models, 0 false alarms from that rule. A measurement artifact of the harness, not a rule fix."
   }
  },
  {
   "id": "rule-short-rows",
   "date": "2026-10-09",
   "time": "10:16",
   "title": "Rule for table rows with a different number of fields than the header",
   "description": "SWAT+ tables whose rows have fewer or more fields than their header are reported as an error. The rule was checked on 12 SWAT+ tables of 137 working models before it was accepted. In the benchmark it closes the last silent-damage fault (hru-data.hru rows lose their last field): 4 of 4 silent faults are now named.",
   "category": "rules",
   "commits": [
    "e938453"
   ],
   "evidence": [
    "git commit e938453",
    "tests/rule_tablerows.test.js",
    "snapshot 2026-10-09T1029_current (case P08_hru_rows_short: ELSEWHERE before, ERROR now)"
   ],
   "source": "git commit e938453",
   "correction": {
    "fixed": "A fault that changed the results without any error or warning about it (P08).",
    "measured_reason": "Benchmark verdict changed from ELSEWHERE to ERROR on P08_hru_rows_short; before it the engine finished and the basin water balance differed from the working model."
   },
   "git_state": {
    "in_working_branch": true,
    "in_published_branch": true,
    "checked": "2026-10-09T10:32"
   }
  },
  {
   "id": "benchmark-current",
   "date": "2026-10-09",
   "time": "10:29",
   "title": "Benchmark with the merged rules: 15 of 15, 4 of 4",
   "description": "The current rules were asked again about the same 22 faulted copies (nothing was run again; the engine outcomes are the saved ones). Faults that stop the engine: cause named in 15 of 15 (as an error in 12 of 15). Faults the run survives but that change results: named in 4 of 4. The 6 unmodified controls got no error. A second, independent re-scoring of the same copies agrees on every case.",
   "category": "benchmark",
   "evidence": [
    "snapshot 2026-10-09T1029_current",
    "bench/compare.py"
   ],
   "source": "ledger snapshot, answers re-asked of the current rules on the saved faulted copies",
   "metrics": {
    "stop_named": 15,
    "stop_cases": 15,
    "stop_as_error": 12,
    "silent_named": 4,
    "silent_cases": 4
   }
  },
  {
   "id": "bench-harness",
   "date": "2026-10-09",
   "title": "Benchmark and audit scripts published, portable and path-free",
   "description": "The benchmark and audit scripts read every location (models, engines, work folder) from one configuration, never from a default path, and the result files contain no absolute paths, so the benchmark can be repeated on another machine with its own models. The pilot table of results was published with them.",
   "category": "tooling",
   "evidence": [
    "bench/README.md",
    "bench/config.py",
    "results/pilot_table.md"
   ],
   "source": "git commit fde6f73 (the harness itself was written on 2026-10-08, per the file times of its first results)",
   "commits": [
    "fde6f73"
   ],
   "time": "10:30",
   "git_state": {
    "in_working_branch": true,
    "in_published_branch": true,
    "checked": "2026-10-09T10:32"
   }
  },
  {
   "id": "ledger",
   "date": "2026-10-09",
   "title": "Evolution ledger and dashboard",
   "description": "One folder with a dated snapshot per state of the tool (rules, tests, audit, benchmark, models), a curated list of milestones and this dashboard, so the progress can be shown as a historical record. Past states were reconstructed only from files that exist; what was never recorded is marked as such.",
   "category": "tooling",
   "evidence": [
    "evolution/ledger/",
    "bench/snapshot.py"
   ],
   "source": "this folder"
  }
 ],
 "milestones_meta": {
  "schema": 1,
  "note": "Hand-curated and chronological. Add new milestones at the end (or in date order); each one names where its numbers come from. Numbers are only those measured in a ledger snapshot, printed in a git commit message, or given by the author. 'commits' lets the dashboard check live whether a change is merged into the working branch and into main (the published branch).",
  "integration_branch": "multi-model",
  "published_branch": "main",
  "categories": {
   "characterization": "Model characterization",
   "rules": "Rules",
   "audit": "Precision audit",
   "benchmark": "Benchmark",
   "design": "Design",
   "publication": "Publication",
   "tooling": "Tooling"
  }
 }
};
